python_examples/correlation_tracker.py, tools/python/CMakeLists.txt, tools/python/src/correlation_tracker.cpp, tools/python/src/dlib.cpp, tools/python/src/gui.cpp, tools/python/src/object_detection.cpp, tools/python/src/rectangles.cpp, tools/python/src/shape_predictor.h
This adds a very simple Python interface for the correlation tracker. It also handles adding the drectangle class and a small update to the GUI code so that drectangles can be visualized.
=> Add a Python interface for the Correlation Tracker

dlib/bayes_utils/bayes_utils_abstract.h
Just a minor adjustment in the documentation.
Thanks for a great library!
best regards
Chris Paprocki
=> Fixed a minor typo in the spec.

setup.py
When cmake is not found, the error message suggests what to do to
install cmake. But if `distro` is not found and cannot be installed,
the distro specific error message cannot be shown. Hence, we simply
ignore this and continue on.
Also, make the pip install quiet so that if there is an error message
in that, the user does not get confused by it.
=> setup.py: Don't fail if pip fails in cmake err msg

dlib/image_processing/render_face_detections.h
Updated comments to specify the position of points on the face for 68 points generated by the face landmark detector.
=> Updated comments to specify the position of points

dlib/image_saver/save_png.h, dlib/matrix/matrix_utilities.h, dlib/pixel.h, dlib/test/pixel.cpp
I have created new type of pixel. This pixel represents color in CIELab color space.
=> Added support for CIELab color space pixels.

dlib/dnn/layers.h, dlib/dnn/layers_abstract.h
Added interface to resolve #208. Is it fit for merge?
=> Adding specific parameters interface on fc_ layer

tools/imglab/src/main.cpp
I hope no one figures out my evil plan of becoming a contributor, by doing the smallest possible change.
=> fixed warning about unsigned-signed comparison in imgtool

README.md
Added Travis badge to the top of Readme.md ![badge](https://travis-ci.org/davisking/dlib.svg?branch=master)
=> Update Readme.md  - travis badge

dlib/dnn/loss.h, dlib/dnn/loss_abstract.h, dlib/test/dnn.cpp
Added mean squared loss layer "loss_mean_squared" to
DNN as requested in https://github.com/davisking/dlib/issues/152
Also added test case of a simple linear regression with one variable
that uses this layer.
=> feature_addition : Added a mean squared loss layer to DNN with test case

dlib/CMakeLists.txt
Problem: See #363.
Solution: Don't set `CUDA_HOST_COMPILER` when targeting Visual Studio.
=> Fix #363 by not setting CUDA_HOST_COMPILER when targeting Visual Studio

dlib/dnn/loss.h, dlib/dnn/loss_abstract.h, dlib/test/dnn.cpp
* Added separate loss_mean_squared_multioutput layer class to support multiple outputs.
* Also added a corresponding test case to test a single variable regression
with multiple outputs.
=> feature_addition : Mean squared loss layer for multiple output (#404)

python_examples/face_recognition.py
Super tiny PR to remove some unneeded semicolons in the new python example that I noticed while testing it.
Feel free to close / reject this PR if you don't care.
=> Remove extra semicolons

dlib/graph_cuts/min_cut.h, dlib/matrix/lapack/gees.h, dlib/test/tuple.cpp
Fixes issue https://github.com/davisking/dlib/issues/536
=> Fixes issue with object named nil that collide with apple's definition.

dlib/simd/simd4f.h, dlib/simd/simd4i.h
This is possible extension to #611. Works well on Tegra TK1
I can't test it with CLang, @nidegen , please test it on your target machine
=> Possible CLang fix for Neon-based SIMD4i

dlib/control/mpc.h, dlib/matrix/matrix_la.h, dlib/optimization/optimization.h, dlib/optimization/optimization_solve_qp_using_smo.h, dlib/test/matrix2.cpp
I need to test it out before the merge request. Just to get the ball rolling on code review.
=>  differential std::clamp from c++17 with dlib:: prefix to clamp()

dlib/geometry/point_transforms.h
point_transforms.h is not self compiling without including drectangle.h
=> Include drectangle.h to point_transforms.h

dlib/array2d/array2d_kernel.h, dlib/array2d/array2d_kernel_abstract.h, dlib/noncopyable.h
Now that C++11 is required to build dlib, I would like to add some features to help with better type traits.
=> C++11 features

python_examples/face_alignment.py, python_examples/face_clustering.py, tools/python/src/face_recognition.cpp
Thank you for accepting my earlier code and adding it to dlib.
Here I have just added the size and padding as optional parameters for save_face_chip
=> Image alignment and saving using Python

dlib/dnn/layers.h, dlib/dnn/layers_abstract.h
(implementation essentially copied from con layer)
=> cont layer: allow to set the number of filters at runtime

dlib/svm/svm_threaded.h, dlib/svm/svm_threaded_abstract.h
=> Allow cross_validate_trainer_threaded to use non-double data

dlib/gui_widgets/widgets.cpp
Just removed the offending unused variable. Not sure it is the way to fix it but it suppress some warning.
=> Remove unused variable

dlib/test/dnn.cpp
This fix suggested by davisking make unit tests more reliable. Fix issue https://github.com/davisking/dlib/issues/925
=> Fix issue https://github.com/davisking/dlib/issues/925

dlib/dnn/loss.h
Solution: limit the input of the log function to 1e-6 (or more)
=> Problem: log loss may become infinite, if g[idx] goes zero

dlib/image_transforms/colormaps.h
Still hunting down pre-generic_image implementations
=> generic image all the way - colormaps.h

dlib/CMakeLists.txt
look at issue:
https://github.com/davisking/dlib/issues/674
=> don't look for OpenMP with Apple Clang

dlib/global_optimization/upper_bound_function.h, dlib/global_optimization/upper_bound_function_abstract.h
Dear Davis,
this PR makes two little corrections to the code of the global optimization module.
Best regards,
Ernesto.
=> little corrections in global optimization

tools/python/src/cnn_face_detector.cpp
I added a python binding for the set_dnn_prefer_smallest_algorithms() function!
=> Added set_dnn_prefer_smallest_algorithms()

setup.py
=> Allow to set arbitrary cmake opts from setup.py

tools/python/src/numpy_returns.cpp
Fix for https://github.com/davisking/dlib/issues/1220
@davisking @supervacuus
=> Fixed reference count issue

tools/python/src/face_recognition.cpp
Hi Davis!
As always, feel free to voice any criticism, opinion, or suggestion for improvement, or to ask any question you might have.
Have a great day!
=> Allow batched face recognition for greater performances

dlib/dnn/loss.h, dlib/dnn/loss_abstract.h
[Previous PR](https://github.com/davisking/dlib/pull/1537)
=> Added weighted labels to loss_binary_log layer.

tools/python/src/face_recognition.cpp, tools/python/test/test_chinese_whispers.py
Boilerplate code to expose chinese_whispers from Python
=> Exposing chinese_whispers directly, closes #1642

dlib/cuda/cuda_dlib.h
=> Semantic-segmentation loss calculation: fix buffer usage on multi-GPU training

docs/docs/imaging.xml
This should close https://github.com/davisking/dlib/issues/1828
=> fix mismatch between documentation and implementation of load_image

dlib/cuda/cuda_dlib.h
Also made `buf` a member variable.
=> Fix #1849 by calling device_global_buffer() unconditionally

dlib/dnn/loss.h
Consider two truth rects that overlap heavily (say, A and B). Also consider basically good response, i.e. two detections (say, C and D) that are pretty close to the truth rects. Now in the current `master` version it may very well happen that both detections C and D happen to be closest to A (and not B), meaning that there's one false positive (both C and D mapped to A) and also one false negative (B not found at all).
This PR modifies the matching process so that detections are primarily matched to truth rects that haven't been hit already. Therefore, detection D (previously false positive) would now be matched to truth rect B (while det C is still matched to truth A), meaning that there's no longer a false positive, and no longer a false negative (assuming of course that …
=> Primarily match to truth rects that haven't been hit already

dlib/dnn/trainer.h
Add minor sanity check in wake of trainer changes introduced as part of #1918.
=> Add minor sanity check

dlib/dnn/layers_abstract.h
Should this be affect instead of effect?
=> effect -> affect

dlib/cuda/cpu_dlib.cpp, dlib/cuda/cpu_dlib.h, dlib/cuda/cuda_dlib.cu, dlib/cuda/cuda_dlib.h, dlib/cuda/tensor_tools.cpp, dlib/cuda/tensor_tools.h, dlib/dnn/layers.h, dlib/dnn/layers_abstract.h, dlib/test/dnn.cpp
This PR adds the leaky_relu activation layer, which is mostly useful for generative models.
It is my first step towards implementing the DCGAN example in #1776.
=> add leaky_relu activation layer

examples/dnn_dcgan_train_ex.cpp
Feel free to close if you don't like it :)
=> use running stats to track losses in dcgan example

dlib/cuda/cpu_dlib.h, dlib/cuda/cuda_dlib.cu, dlib/cuda/cuda_dlib.h, dlib/dnn/loss.h, dlib/dnn/loss_abstract.h, dlib/test/dnn.cpp
Thanks to @reunanen for helping out! :D
=> Add cuda implementation for loss_mean_squared_per_channel_and_pixel

examples/dnn_mmod_ex.cpp
As you noted on #2068, I changed `a little over` to `approximately`.
Thank you!
=> fix receptive field comment according to #2068

dlib/image_transforms/interpolation.h, dlib/image_transforms/interpolation_abstract.h
=> Minor optimization: add shortcut to in-place image resize if size_scale is 1

dlib/rand/rand_kernel_1.h, dlib/rand/rand_kernel_abstract.h
Added a function for computing a gaussian distributed complex number.
The real version is adapted to use the complex version.
=> Added "get_random_complex_gaussian" to dlib::rand

dlib/cuda/cudnn_dlibapi.cpp
num_possi**lb**e_algorithms -> num_possi**bl**e_algorithms
=> Minor typo fixes

dlib/dnn/trainer.h
**Problem:** I had a rare opportunity to test a 8-GPU machine. I copied my scripts from a one-GPU machine. There I had mini-batch size set to 50.
This caused a crash on the 8-GPU machine, because the mini-batch was allocated as 50 = 7 * 7 + 1, and the batch with size = 1 wasn't good for batch normalization.
Yes, I know that on the 8-GPU machine, I'm better off setting the mini-batch size e.g. to 8 * 50 = 400. However, I didn't immediately realize that this was the problem (the crash error message wasn't particularly helpful), and it took me quite a while to even get debugging started on this new-to-me machine.
**Suggested solution:** Divide the mini-batch more uniformly across the different devices.
=> Divide mini-batches more uniformly across devices

dlib/dnn/core.h, dlib/dnn/core_abstract.h, dlib/dnn/layers.h, dlib/dnn/layers_abstract.h, examples/dnn_dcgan_train_ex.cpp
As I explained in #2155, this PR adds a visitor that will automatically remove bias learning from all layers that are inputs of `bn_` layers.
=> Add visitor to remove bias from bn_ layer inputs (#closes 2155)

examples/dnn_dcgan_train_ex.cpp
Following your example in this [reddit thread](https://www.reddit.com/r/dlib/comments/in0upc/setup_lealy_reluprelu_activation_layers_in_a/), I've updated the dcgan example to show how to setup `leaky_relu_` layers using the new style visitors with a lambda.
I think it's worth having because the 2nd introduction already shows how to do with the network constructor.
=> Show how to use the new visitors with lambdas

dlib/cuda/cpu_dlib.cpp, dlib/cuda/cuda_dlib.cu
Also, apply same changes on the cpu side.
=> Do not use sqrt_2 in device code (fixes #2208)

dlib/console_progress_indicator.h
Would this be enough to address #2232?
=> Add custom ostream to console progress indicator (closes #2232)

dlib/serialize.h, dlib/test/serialize.cpp
This resolves issue https://github.com/davisking/dlib/issues/2243
=> Fixes bug when (de)serializing vector<complex<float>>

dlib/CMakeLists.txt, dlib/all/source.cpp, dlib/data_io.h, dlib/data_io/cifar.cpp, dlib/data_io/cifar.h, dlib/data_io/cifar_abstract.h, dlib/data_io/mnist.cpp
I thought this would be nice to have to test easily on CIFAR-10.
=> Add CIFAR-10 dataset loader

dlib/image_transforms/draw.h, dlib/image_transforms/draw_abstract.h, dlib/test/image.cpp
As discussed in #2264 with @pfeatherstone.
It's almost the same as the one defined in `fonts.h` for the gui widgets.
=> Draw string on images

dlib/matrix/matrix_fft.h, dlib/matrix/matrix_fft_abstract.h, dlib/test/fft.cpp
=> FFT: added std::vector overloads for fft, ifft, fft_inplace and ifft_inplace

dlib/dnn/utilities.h, dlib/test/dnn.cpp
I guess this was broken at some point, but it works now :)
=> fix set_learning_rate_multipliers_range not working

dlib/serialize.h, dlib/test/dnn.cpp, dlib/test/matrix.cpp, dlib/test/serialize.cpp, dlib/test/vectorstream.cpp, dlib/vectorstream/vectorstream.h
Hopefully this time it's done properly.
=> Serialization to and from vector<int8_t> and vector<uint8_t>

dlib/vectorstream/vectorstream_abstract.h
@davisking Sorry i didn't do this in the last PR.
=> [SERIALIZATION] updated vectostream_abstract

dlib/matrix/matrix_math_functions.h, dlib/matrix/matrix_math_functions_abstract.h, dlib/test/matrix.cpp
Closes #2319.
Still not convinced about the function name, though.
=> Add softmax function for matrix type

dlib/dnn/utilities.h, dlib/test/dnn.cpp
=> Fix input/output mappings with repeat layers

dlib/cuda/cpu_dlib.cpp, dlib/cuda/cpu_dlib.h, dlib/cuda/cuda_dlib.cu, dlib/cuda/cuda_dlib.h, dlib/cuda/cudnn_dlibapi.cpp, dlib/cuda/cudnn_dlibapi.h, dlib/cuda/tensor_tools.cpp, dlib/cuda/tensor_tools.h, dlib/dnn/layers.h, dlib/dnn/layers_abstract.h, dlib/test/dnn.cpp
This PR will add the following activation layers, already present in CUDNN:
- clipped_relu
- elu
Progress:
=> Add Clipped ReLU and ELU activations

dlib/cuda/cpu_dlib.cpp, dlib/cuda/cuda_dlib.cu, dlib/dnn/layers.h, dlib/dnn/layers_abstract.h, dlib/test/dnn.cpp
Sorry for spamming, I didn't notice that we could also make ELU an inplace layer...
=> Make ELU an inplace layer and fix Clipped ReLU implementation

dlib/serialize.h, dlib/test/serialize.cpp
=> [SERIALIZATION] added support for std::variant

dlib/serialize.h
I got a compiler error because of a small typo.
=> Fix serialize variant with C++17

dlib/travis/build-and-test.sh
If this worked, the code should not compile with C++17. See #2365.
=> Make Travis read the CXXFLAGS enviroment variable

dlib/CMakeLists.txt
=> Fix cannot compile iso only code (#579)

dlib/cuda/tensor_tools.h
I just realized I never added the documentation to the LayerNorm layer.
I also corrected a couple of typos in the batch_normalize function documentation.
=> Add LayerNorm documentation

dlib/cmake_utils/find_blas.cmake
Add some paths in find_blas.cmake with new Intel mkl library.
From here: [https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html](url)
Tested on dnn_imagenet_ex.
=> Add intel mkl search path

dlib/dnn/trainer.h
Let's see if the tests pass on this one. It works on my machine.
I will then try to figure out a way of reusing the code between `send_job` functions
=> Fix trainer with unsupervised loss

dlib/dnn/loss.h
I noticed there were some computations that didn't depend on the output tag layer and the input tensor area was computed over and over inside of a loop.
=> Avoid redundant computations in the YOLO loss

dlib/invoke.h, dlib/test/CMakeLists.txt, dlib/test/invoke.cpp, dlib/utility.h
=> [INVOKE] C++11 backport of std::invoke, std::invoke_result, std:apply and std::make_from_tuple

examples/dnn_self_supervised_learning_ex.cpp
As you recommended, I replaced the sgd-based fc classifier with svm_multiclass_linear_trainer.
You were right, after setting the right C parameter, it results in higher accuracy while training orders of magnitude faster.
(that book is already ordered!)
Thank you :)
=> Replace sgd-based fc classifier with svm_multiclass_linear_trainer

tools/python/src/other.cpp
Prior to this patch, Kalman filtering has been only available in Python using `rect_filter`, which makes filtering a floating-point scalar rather clumsy.
I pretty much only copied parts of existing code. It was my first contact with pybind11 so I hope the result is appropriate.
=> expose momentum_filter to Python

dlib/dnn/loss.h
This PR fixes a small bug where `yolo_options::lambda_obj` was not being used in the `ignore_iou` case.
It's not a big deal, since the example uses the default value of 1, but still.
I also performed some refactoring to be more clear and reuse some computations.
=> Use lambda obj in the ignore case and do some refactoring

dlib/dnn/loss.h
This bug has been bothering me for quite some time… It took me a really long time to figure out why the training was randomly crashing (when I used strong data augmentation).
I don't know if we should warn the user that we're ignoring these truth boxes… but we shouldn't try to back propagate on them, for sure.
=> Fix a crash when the truth center is outside the image

dlib/cuda/cpu_dlib.cpp, dlib/cuda/cuda_dlib.cu, dlib/dnn/layers.h, dlib/test/dnn.cpp
Solves #2486.
Fixes Layer Norm, introduced in #2213.
For this PR, I've decided to not over do it and just fix the implementation. Maybe at some point I will check if it's worth to add dimensionality options.
=> Fix Layer Normalize

dlib/dnn/loss.h
I was re-reading the YOLOv4 paper, and came across the concept if grid sensitivity, which I somehow overlooked before.
This issue contains a good explanation: https://github.com/AlexeyAB/darknet/issues/3293.
The main idea is that, if an object has the center of its bounding box exactly on the grid lines, the center regression will not be able to detect it.
The reason is that the network will have to output either 0 or 1 for x and y, respectively, which is impossible, being the output of a sigmoid.
To solve this problem, we can just scale and shift the sigmoid function to allow the x and y outputs to range between -0.5 and 1.5 like this: output = sigmoid(input) * 2.0 – 0.5.
According to the experiments run by @AlexeyAB and @glenn-jocher, it mitigates this issue, while improving the AP a …
=> Eliminate grid sensitivity in YOLO

dlib/external/pybind11/include/pybind11/numpy.h
Fixes missing ssize_t definition on Windows
=> Resolve davisking/dlib#2463

docs/docs/imaging.xml, docs/docs/ml.xml, docs/docs/term_index.xml
Oops, in my previous PR I missed the `input_rgb_image_pair` layer.
=> Add input_rgb_image_pair layer and new net visitors documentation

dlib/dnn/loss.h
I noticed that, when using high dimensional features (such 8192), the Barlow Twins loss takes a really long time to compute on GPU. This issue is not noticeable with lower dimensional features, such as 128, like in the example.
That is because, at each step, many tensors are allocated, and copied to the GPU.
I've modified the computations so that only the first step allocates the tensors.
Since the `compute_loss_and_value_gradient` is a `const` method, I had to make the `resizable_tensor` member variables `mutable`… However, if the size of the input changes, the tensors will be reallocated and recomputed.
I hope you are OK with this modification.
In my case, `num_samples == 64` and `k == 8192`, it makes the network train almost 10 times faster.
I am open to some other optimization …
=> Speed up Barlow Twins loss

dlib/cmake_utils/dlibConfig.cmake.in
While I am not a cmake expert (and certainly not camke 2.x) I thought I'd give it a go.
=> Find Threads target if necessary (#2522)

dlib/dnn/loss.h
The loss value should reflect the impact of the gamma parameter as well.
I was too “focused” on getting the gradient right, that I forgot about the loss…
=> Fix focal loss

dlib/dir_nav/dir_nav_extensions.cpp, dlib/dir_nav/dir_nav_extensions.h, dlib/dir_nav/dir_nav_extensions_abstract.h, docs/docs/api.xml, docs/docs/release_notes.xml, docs/docs/term_index.xml
I think it can be handy, and it provides some kind of consistency with the already present `file_exists`.
=> Add directory_exists

dlib/cuda/tensor_tools.cpp
I don't know how I could miss this.
=> Use CUDA in LayerNorm gradient computation

.github/workflows/build_cpp.yml
=> Build ancillary tools on Windows

dlib/type_safe_union/type_safe_union_kernel.h, dlib/utility.h
=> [TYPE_SAFE_UNION] fix spelling

dlib/math/bessel.h
This should fix the issue raised in #2627
=> Bessel fix for MSVC

dlib/cmake_utils/find_libwebp.cmake, dlib/cmake_utils/test_for_libwebp/CMakeLists.txt, dlib/cmake_utils/test_for_libwebp/libwebp_test.cpp, dlib/image_loader/webp_loader.cpp
=> Add test for libwebp at configure time

dlib/dnn/layers.h
Fixes #2655.
Somehow, doing it in a single call is slower.
=> Do the bias addition in the convolution in a separate call

dlib/dnn/loss.h, examples/dnn_self_supervised_learning_ex.cpp
When computing the gradient for the off diagonal terms, I forgot one transpose:
`A' * B = C`, but `B' * A = C'`
=> Fix computation of the Barlow Twins loss gradient

examples/dnn_self_supervised_learning_ex.cpp
I was using the data augmentation recommended for the ImageNet dataset, which is not well suited for CIFAR-10.
After doing so, the test accuracy increased by 1 point.
=> Improve the data augmentation in the SSL example

dlib/cuda/cuda_utils.h
Fixes #1984 
Additionally improves regression status (on my pc) from: 
```
$ ./dtest  --runall 
Running test_dnn |                                                             
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEST FAILED: test_dnn !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Failure message from test: Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /home/michal/projects/sources/dlib/dlib/cuda/gpu_data.cpp:221. code: 2, reason: out of memory
Running test_ranking \                                                         
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! …
```
=> Fix for issue #1984

dlib/config.h.in
=> ffmpeg wrappers - fixed config.h.in

dlib/statistics/statistics.h, dlib/statistics/statistics_abstract.h
I know I could've gotten around by using `mean` and `current_n`, but I felt like it would've been more convenient to have it.
=> Add sum method to running stats

tools/imglab/src/main.cpp, tools/imglab/src/metadata_editor.cpp, tools/imglab/src/metadata_editor.h
=> Add support for loading custom label fonts in imglab

tools/python/src/face_recognition.cpp
I wanted to use bottom up clustering in a python script but realized it wasn't present (yet) so I figured I'd go ahead and implement it. Happy to tweak or adjust if need be.
=> Added bottom_up_cluster to python api

examples/CMakeLists.txt, examples/ffmpeg_rtsp_ex.cpp
=> FFmpeg : RTSP example

dlib/media/ffmpeg_utils.h
I was getting a warning about this.
=> Silence warning about unused variable

dlib/media.h, dlib/media/ffmpeg_demuxer.h, dlib/media/ffmpeg_utils.h, examples/CMakeLists.txt, examples/ffmpeg_file_to_speaker_ex.cpp, examples/ffmpeg_microphone_to_file_ex.cpp
=> FFmpeg : examples

dlib/gui_widgets/widgets.cpp, dlib/image_transforms/draw.h, tools/imglab/src/metadata_editor.cpp
Oops, I missed these, sorry :(
=> Update widgets and draw_string on images to use convert_to_utf32

dlib/media/ffmpeg_abstract.h, dlib/media/ffmpeg_demuxer.h, dlib/media/ffmpeg_muxer.h, dlib/media/ffmpeg_utils.h
Would you be interested in such functions?
=> Add ffmpeg load_frame

dlib/constexpr_if.h, dlib/test/invoke.cpp, dlib/type_safe_union/type_safe_union_kernel.h, dlib/type_traits.h
This is going to come in handy in a second.
=> [Meta] added callable traits

dlib/type_traits.h
=> [Traits] missing include

tools/python/src/numpy_returns.cpp
=> Python: Add grayscale overloads to get_face_chip

examples/ffmpeg_webcam_face_pose_ex.cpp
Fixes https://github.com/davisking/dlib/issues/2865
=> [FFMPEG] bug fix in webcam example

dlib/scope.h, dlib/test/CMakeLists.txt, dlib/test/scope.cpp
Adding https://github.com/davisking/dlib/discussions/2874
=> [scope] Adding scope_exit

dlib/media/ffmpeg_demuxer.h
Fixes https://github.com/davisking/dlib/issues/2945
=> [FFMPEG] fixed bug in decoder

dlib/misc_api/misc_api_kernel_1.cpp, dlib/threads/threads_kernel_1.cpp, dlib/threads/threads_kernel_1.h
To resolve https://github.com/davisking/dlib/issues/2950
=> Hide windows.h in .cc file

setup.py
May solve stuff like https://github.com/davisking/dlib/issues/2977
=> Disable FFmpeg support when building the Python wheel

dlib/image_transforms/interpolation.h
=> add serialization support to chip_details
