davisking/dlib

python_examples/find_candidate_object_locations.py
tools/python/src/object_detection.cpp

Hi Davis,
This PR is for adding find_candidate_object_locations() to dlib's Python API. An example of how to use it is also included. There are a couple of things that I'd like to mention:
1) As shown in the comment, pykvals in the Python API is different from kvals in the C++ code. pykvals is actually a Python tuple (start, end, num) for linspace(start, end, num). I'm not sure whether dlib provides a Python object for matrix_range_exp.
2) Locations of candidate objects (rects) should be the result of find_candidate_object_locations_py() rather than its argument. However, I think it's better to be consistent with dlib's C++ API.
Please take a look and let me know whether I need to change something.
Thanks.

Adding Python-binding for find_candidate_object_locations

---

dlib/cmake_find_blas.txt

For whatever reason, the standard yum-installed ATLAS libraries were renamed for RHEL/CentOS 7.0.

Locate ATLAS on RHEL/CentOS 7

---

python_examples/face_detector_scores_idx.py
tools/python/src/object_detection.cpp
tools/python/src/simple_object_detector_py.h

- Added a second version of `run_detector_with_upscale()` so it can return additional vectors (via pass by reference)
- Modified the code that actually runs the detector -- I call the version that returns rect_detections
- Added code to split rect_detections into three vectors: rectangles, scores, and weight_indices
- Added a python example program that shows how to use the new bindings
- Rather than loading the image with skimage, I used Pillow because Pillow does not depend on scipy which takes a long time to build.

Add capability to get detection confidences and weight index in python

---

dlib/test/pipe.cpp
dlib/test/read_write_mutex.cpp
dlib/test/timer.cpp

c++11 std::mutex clashes with dlib::mutex when:
using namespace std;
using namespace dlib;

Fix dlib tests for c++11

---

dlib/cmake

When using add_definitions erroneous flags are passed to dll resource compiler under MinGW. This breaks the build for anything linked to dlib, using a dll rc and MinGW.
The proper way is to append to CMAKE_CXX_FLAGS. For a discussion on this see:
http://www.cmake.org/pipermail/cmake/2011-July/045532.html
For CMake 2.8.12 and higher the proper way is add_compile_options(-Wreturn-type) OR target_compile_options(dlib PRIVATE -Wreturn-type)

Replace add_definitions with CMAKE_CXX_FLAGS in cmake file

---

docs/README.txt

This MR removes the link to the (old and inaccessible) sourceforge mercurial repository and uses the new GitHub address.

Removes link to sourceforge mercurial repository

---

dlib/serialize.h

Include "unicode.h" twice in serialize.h. Remove the redundant one.

Remove redundant include

---

dlib/CMakeLists.txt

Using CMAKE_PROJECT_DIR instead of CMAKE_SOURCE_DIR/../dlib
makes the build process more portable.
1. If dlib is used as subdirectory of another project CMAKE_SOURCE_DIR will point to a different path then expected in the original code. 
2. If for some reason the dlib directory is renamed configuring would break which is at least more restrictive than necessary.

Change relative path of configure files in CMakeLists.

---

dlib/smart_pointers/shared_ptr.h
dlib/smart_pointers/shared_ptr_thread_safe.h

Add pragma guards around deprecated auto_ptr to prevent GCC warnings

---

setup.py

Please use sys.stdout.encoding instead of latin-1 in setup.py.
This is necessary for non English OS.

sys.stdout.encoding instead of latin-1 in setup.py

---

setup.py

When python does not know the encoding of stdout, sys.stdout.encoding
is None.  Then calling decode(None) raises an exception.  We just
skip decoding when the encoding is unknown.

Decode message only if encoding is known

---

dlib/geometry/drectangle.h
dlib/geometry/drectangle_abstract.h
tools/python/src/dlib.cpp
tools/python/src/rectangles.cpp
tools/python/src/shape_predictor.cpp
tools/python/src/shape_predictor.h

Addresses #65. Simply added the `(self == self)` Macro syntax and add equality operators to `drectangle` in the main dlib source - copied from rectangle.
Also, sneak in two other changes:
- Make `shape_predictor_training_options` serializable and printable.
- Add `__version__` attribute to the dlib Python module to be compatible with PEP 396. Only issue is that the string is hard coded - maybe someone can think of a better way to read it from the `CMakelists.txt` at compile time (@davisking)

Drectangle equality

---

setup.py

I was having trouble getting `python setup.py install` to build a usable library on OS X. Loading the shared object would seg fault. I use a brewed Python, but cmake would default to using the system python lib under /usr/lib. Forcing a non-default -DPYTHON_LIBRARY is one solution that seems to work. There may be other, better ways to accomplish this but this change works for me.

detect OS X, and query sysconfig for libdir

---

dlib/matrix/matrix_qr.h
dlib/test/matrix4.cpp

Dear Davis,
The code
~~~
dlib::matrix<double,5,5> M;
...
dlib::orthogonalize(M);
~~~
generates the following compilation error:
~~~
dlib/matrix/matrix_la.h:833: error: no matching member function for call to 'get_q'
qr_decomposition<matrix<T,NR,NC,MM,L> >(m).get_q(m);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
...
dlib/matrix/matrix_qr.h:65: candidate function not viable: no known conversion from 'matrix<double, 5L, 5L, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>' to 'matrix_type &' (aka 'matrix<type, 0, 0, mem_manager_type, layout_type> &') for 1st argument
void get_q (
^
~~~
The code in this pull request attempts to resolve the aforementioned issue.
Best regards,
Ernesto.

orthogonalize does not work with fixed-sized matrices

---

CMakeLists.txt
dlib/CMakeLists.txt

This pull request contains a couple changesets to get dlib to build:
1. as and External Project
2. with a cross-toolchain (I've tested with the linaro-multilib-2014.06-gcc4.9 ARM toolchain)

Support use of dlib a cross-compiled ExternalProject

---

dlib/image_transforms/fhog.h

I found being able to threshold the rendering of individual orientations in `draw_fhog(...)` quite useful for debugging.

introduce a configurable threshold for rendering HOGs

---

tools/python/src/object_detection.cpp
tools/python/src/simple_object_detector.h

When fine-tuning object detector, I need to run training may times. With some combination of options, trainer starts upsampling images 1-2 times that makes trainer to crash due to available RAM limitations.
Original trainer had hard-coded upsample limit value == 2. 
I changed this to options, with default value == 2
With this feature, we can control RAM usage limiting upsample function

Python/Simple object detector trainer. Added upsample_limit option

---

dlib/simd/simd_check.h

Some processors (Atoms/Pentiums) does not support AVX but support SSE2
When I compile face detector with MSVC, x64 - compiler gives me SSE2 support
To enable it in Dlib, i need to put "DLIB_HAVE_SSE2" into preprocessor definitions, otherwise face detector will be 2-3x slow
When building samples with CMAKE, I have this definition by default, but I can forget about it in real project, and I didnt find dlib's documentation about enabling only SSE2 without AVX
With this PR I am enabling SSE2 support for all x64 builds in MSVC, even when AVX is not enabled

MSVC x64 SSE2 automatical support

---

dlib/image_transforms/fhog.h

I found that FHOG module mixes doubles and floats in many places. This makes compiler harder to optimize the code. And we do not use more than 4-5 significant digits in float values
I think, we can use float instead of double here. All result HOG features were already float
My measurements (based on my previous PR measurement method):
MSVC 2013, Windows 7, 64bit, i7/2.5Ghz:
1) Release, x64 /O2 /arch:AVX : **1482** msec - this is master branch, if added AVX
2) Release, x64 /O2 : **1624** msec - master branch as-is
3) Release, x64 /O2 (without my recent PR#91 and without /DDLIB_HAVE_SSE2) : **6782** msec (much slower than 2)
4) Release, x64 /O2 (with PR#91 and without /DDLIB_HAVE_SSE2) : **1624** msec (same as 2)
5) Release, x64 /O2 (with PR#91 fhog-float branch): **1517** msec (6.6% faster …

Using float instead of double for FHOG computations

---

dlib/test/CMakeLists.txt
dlib/test/corellation_tracker.cpp

I am interested in using corellation_tracker. But it is extremely slow with my data
I want to improve its performance, but before doing it we need to create regression tests
This test simply uses 4 frames from examples/video_frames folder and checks if tracking is the same as recorded one. I dont want to generate images, I think that using real data will make better results
Do I need to add more frames? This test works now < 1 sec, but cpp file is 81kb, each frame is about 17 kb
Tested with GCC 5.2, MSVC2013x64, MSVC 2015x64 (with #96 ) and MSVC2015 x86 (with #96)

Regression test for corellation tracker

---

dlib/image_processing/correlation_tracker.h
dlib/image_processing/correlation_tracker_abstract.h

Default behaviour of tracker didnt changed
I added some options to corellation_tracker constructor to control the size of filters and other params
And I made new update_noscale function that will track only object position without tracking scale
This small changes makes tracker work 20x faster on my data, where scale didnt change at all and filter size should be small
I am not creating separate struct for options, but it can be done if needed
I need options to be parameters to change them at runtime with contructing new tracker object. This will make the final user able to change them

Corellation tracker options

---

dlib/image_transforms/fhog.h

FHOG module is based on simd4 and works well. I am adding simd8 usage if DLIB_HAVE_AVX is defined
MSVC 2013, Windows 7, x64 - performance is about **3-4%** better (not much, but little better)
GCC 5.2, Ubuntu x64 - performance is about **12 %** better (i think, it is much better)
So, with my previous PR's, the overall performance is expected to be 20% better on AVX processors - as on Linux, as on Windows
BTW, GCC/Ubuntu build works about 20% faster than MSVC/Windows
For performance testing i am running 100 iterations of detector with 2007_007763.jpg from examples/faces folder. MSVC time is about 12 seconds, GCC - 9.7 seconds on my laptop
Regression test:
Release\dtest.exe --test_fhog
Testing Finished
Total number of individual testing statements executed: 175037700
All tests completed …

Added simd8 usage on FHOG features computation

---

dlib/CMakeLists.txt
dlib/cmake_find_blas.txt
dlib/dlib.pc.in
dlib/test/makefile

* Add **pkg-config** file, allowing for build-system agnostic dependencies
This is important, as most build systems are not CMake and therefore asking users to employ CMake merely for one dependency is not optimal. In addition, I have versioned the .pc file, such that the library may be installed in parallel, should the API change substantially. This is considered good practice and done by all major libraries (GTK+ for instance). See also https://tecnocode.co.uk/2014/12/09/a-checklist-for-writing-pkg-config-files/
* Define `LIB_INSTALL_DIR` cache variable, allowing for multilib installations
This is important for distributions like Gentoo, where we might install 32-bit and 64-bit libraries simultaneously. Nevertheless, the default remains `lib/`, so unless the user specifies …

Augment build-system, allow for multilib installation, support pkg-config discovery

---

dlib/dnn/trainer.h
dlib/dnn/trainer_abstract.h

When training with train_one_step(), I want to make some extra testing every 1000 calls (example value). I want to use counter provided by trainer, because it is serialized into syncronization file and restored from it if process is restarted

Added getter for trainer::train_one_step_calls

---

dlib/image_saver/save_jpeg.cpp

In some verisons on jpeg, TRUE is an enum, and so `true`
fails because it is not of the enum's type. Now, all the
libjpeg calls use TRUE/FALSE.
Fixes https://github.com/davisking/dlib/issues/129

save_jpeg: Use TRUE instead of true

---

setup.py

If cmake_path is not found, either cmake is not installed
or cmake is not in the PATH. Hence, we also give instructions
on how to install cmake if the path is not found.
Fixes https://github.com/davisking/dlib/issues/132

setup.py: Provide instructions to install cmake

---

dlib/image_processing/shape_predictor.h

move friend method searialize and desearialize implement outside the shape_predictor, so that we can use the  not only `desearialize` but also `dlib::desearialize`.
in fact, in the current master branch, if use as follow:
```cpp
istringstream in("model_string");
dlib::deserialize(sp, in);
```
The compiler will report ` error: no matching function for call to ‘deserialize(dlib::shape_predictor&, std::istringstream&)’` error.
this pull request fix this bug.

fix shape_predictor dlib::searialize and dlib::desearialize error

---

dlib/python/numpy.h
dlib/python/numpy_image.h

One problem is the function name `get_numpy_ndarray_parts` suggests that its a generic function. While I have to check for pixel type's consistency where  I assume the array to be no more than 3-D before copying the data. Otherwise, Python core dumps.  I know we could assign the pointer outside the function but that means we need to change the function prototype. So is this PR acceptable?

Spport to discontiguous Numpy arrays

---

dlib/image_processing/shape_predictor.h
dlib/image_processing/shape_predictor_abstract.h
examples/train_shape_predictor_ex.cpp

I need to train some shape predictor and I found that this process is very slow for me - up to 5-6 days with 64 GB RAM usage. Also training process uses a lot of RAM
With this PR I made this changes:
1. training_sample::feature_pixel_values was float-based. Now I am using the type provided by image_traits. In the most cases - it is unsigned char leading to lower RAM usage (about 15% less summary with all other changes). Train_shape_predictor_ex uses 400 features inside each sample (1600 bytes was, now - 400)
2. some parts of trainer uses the shape difference training_sample::target_shape - current shape. And this differenct is recalculated for the same sample many times. I made caching for it inside training_sample::diff_shape. This increases RAM usage a little (+68*2*4 = 544), and …

Shape predictor trainer optimizations

---

dlib/misc_api/misc_api_kernel_1.cpp

This is the only file that doesn't compile when `WIN32_LEAN_AND_MEAN` is defined. Since I define this flag project wide and just include `dlib/all/source.cpp`, it would be cool to make this work.

Make dlib compile with WIN32_LEAN_AND_MEAN defined

---

dlib/dnn/trainer.h
dlib/dnn/trainer_abstract.h

Add an overload of dnn_trainer::train_one_step that takes a pair of
iterators rather than a std::vector.

Add dnn_trainer::train_one_step iterator signature

---

dlib/cmake_utils/use_cpp_11.cmake

Detecting C++11 capabilities did not work on OSX 10.11.6, XCode 7.3.1, Apple LLVM 7.3.0, cmake 3.6.1. First check revealed that CMAKE_CXX_KNOWN_FEATURES was empty, so subsequent matches failed. After reading http://public.kitware.com/pipermail/cmake/2014-November/059182.html changed handling to fetch property instead of relying on variable. Works on my machine.

Fixed detection of C++11 features

---

dlib/sockets/sockets_kernel_1.cpp

Fixed warning about sockets from #235

Fixed warning about winsock2.h in windows build

---

dlib/assert.h

This is to use initializer lists with MSVC 2015.
Also I wonder why [this commit](https://github.com/davisking/dlib/commit/48df23a0e065e01c5ba176d4999fffb0d9a29e02) disabled the C++11 with MSVC? It is quite capable of compiling C++14.

first check large number in elsif

---

setup.py

Now PYTHON_INCLUDE_DIR and PYTHON_LIBRARY setting up correctly for both 32/64 bit architectures

Fix building on win32 with 32bit architecture

---

dlib/cmake_utils/test_for_cudnn/find_cudnn.txt

I have tried the dlib 19.1 with Visual Studio 2015 Update 3, CUDA 8 and cuDNN 5.1. 
I failed configuration of CMake because cuDNN is not found when I installed cudnn in %USERPROFILE%/library/cuDNN/ .
Of course, I added the above path to CMAKE_PREFIX_PATH.
Unzipped cuDNN 5.1 has following directories and files.
(Root directory of cuDNN 5.1)
├─bin ─ cudnn64_5.dll
├─include ─ cudnn,h
└─lib ─ x64 ─ cudnn.lib
So, I added x64 to PATH_SUFFIXES on line 14 in its source code to solve this problem.

find_cudnn modified for cudnn installed a user directory.

---

dlib/threads/async.cpp

Added `#include <thread>`. This can help to exclude possible misunderstanding of MinGW x86 comiplation problems in a future

Fix for #281

---

dlib/image_processing/shape_predictor.h

fix for #280 . train_shape_predictor_ex example compiles well even without this PR. this PR just clarifies the dependancy

Added threads.h into shape_predictor.h

---

dlib/optimization/optimization_line_search.h

If temp is nonzero but a subnormal then temp2 matrix may contain infinities which may cause temp assignment in line 225 to be a NaN (as a difference of two positive infinities).

optimization - poly_min_extrap fixed for a specific case

---

.travis.yml
dlib/travis/before-install.sh
dlib/travis/build-and-test.sh

This PR introduces minimal Travis-CI integration scripts. This was earlier discussed here #118 and didn't got enough attention
I am now using Travis with one other project and I really see that it is usefull to see if incoming PR breaks code or not
Travis will make automatic compilation of dtest (and execute it with --runall) and all examples (no running - build only) on each incoming PR and PR change. Author of PR will show integration result immediately with no need to as Davis to check his code.
This does not replace existing way to test dlib on existing servers, but can be usefull as an additional automatic CI tool visible to PR authors
How to integrate:
1. register on https://travis-ci.org/ with using github account (Free for open-source)
2. "My repositiories" -> press "+" -> select …

Travis CI Integration scripts

---

dlib/image_saver/save_jpeg.cpp

When compiling on windows and using libjpeg compiled outside of dlib you will get - 'INT32': redefinition; different basic types. This tracks back to the fact the jmorecfg.h in the libjpeg source defines INT32 (dlib's source for libjpeg does not included this define), later basetsd.h (from the windows kit) defines it differently. jmorecfg has a pre-processor check against _BASETSD_H_ defined in basetsd.h, however in this case jmorecfg.h gets included before basetsd.h in save_jpeg.cpp through jpeglib.h (includes jmorecfg.h)  and image_saver.h (includes basetsd.h). Swapping the order of the includes seems to fix the issue with no apparent issues created.

Fix include issue when using libjpeg compiled outside of dlib ('INT32': redefinition; different basic types)

---

README.md

This PR updates the Travic CI status badge in `README.md`: Link on CI status badge points to the [Travis CI](https://travis-ci.org/davisking/dlib) page for `dlib` now.
Closes #309

Update Travis CI status badge

---

dlib/test/active_learning.cpp

As described in #313 the `active_learning` tests fails on ARM64. 
This PR increases the number of iterations to make the test more robost.
Closes #313

Made active_learning test more robust on ARM64

---

dlib/test/max_cost_assignment.cpp

The ARM ABI defines a `char` as an unsigned byte, see [ARM spec](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0375g/chr1359124944415.html).
That's the reason why the `max_cost_assignment` test fails on this condition:
```cpp
assign = max_cost_assignment(matrix_cast<char>(cost));
DLIB_TEST(assignment_cost(cost,assign) == true_eval);
```
By changing the `matrix_cast<char>(cost)` declaration to `matrix_cast<signed char>(cost)` the test will succeed.

Fix for failing max_cost_assignment test on ARM/ARM64

---

tools/imglab/src/main.cpp

fixes #321
This PR adds a new `--rm-other-labels` to imglab
The option accepts its argument as:
* either a single string 
* or a comma separated list of labels to keep
Example:
```bash
imglab --rm-other-labels product1 testing.xml
imglab --rm-other-labels "product1,product2" testing.xml
```
> Note
> when using commas, the resulting file name will replace them with dashes
```
imglab --rm-other-labels "product1,product2" testing.xml
``` 
> will generate `tesing.xml-rm-other-labels-product1-product2.xml`

Add option --rm-other-labels to imglab

---

tools/python/src/object_detection.cpp
tools/python/src/simple_object_detector_py.h

This exposes a static method `run_multiple` on `dlib.fhog_object_detector` that accepts a list (python list) of detectors
The results have the same form as for the `run` method
Example:
```python
detector_1= dlib.fhog_object_detector("object_detector1.svm")
detector2 = dlib.fhog_object_detector("object_detector2.svm")
detectors = [detector1, detector2]
retval = dlib.fhog_object_detector.run_multiple(
detectors, 
image, 
upsample_num_times=0,  
adjust_threshold=0.0)
```

Expose python binding for running multiple detectors at once

---

dlib/assert.h

Remove initializer lists support for Apple (libstdc++ version used does not include std::initializer_list). When compiling on Mac an older version of libstdc++ can be linked in that does not included std::initializer_list. Same issue can be seen with Qt (https://git.merproject.org/faenil/qtbase/commit/387f75c39bfad4439a6bd013089c2cd216cda5ea), basically the same fix.

Remove initializer lists support for Apple/libstdc < 4.02

---

dlib/unicode/unicode.h

This PR introduces a GCC pragma for disabling misleading-indentation warnings in the `is_combining_char()` method in `unicode.h`.
On GCC >= 6 the `-Wmisleading-indentation` option was added to `-Wall` and this would cause about 19880 warnings in `unicode.h`.
As discussed in #337 it is ok to disable these warnings via a special GCC `#pragma`.

unicode: Disable misleading-indentation warnings with GCC pragma

---

dlib/CMakeLists.txt
dlib/cmake_utils/cmake_find_blas.txt
dlib/config.h.in
dlib/matrix/matrix_fft.h

Hi Davis,
I recently added bindings to the MKL DFTI library for FFT computation. I'm not 
sure if you want to add MKL specifics to DLIB, but if you're happy to do so, 
then I hope these will be useful. Using DFTI speeds things up for me when using
the correlation_tracker.
I've tested using the version of MKL that comes with Intel Parallel Studio 2017, 
on Ubuntu 16.04.
Tests all pass when built with either -DDLIB_USE_MKL_FFT=ON or -DDLIB_USE_MKL_FFT=OFF;
(p) pal181@prodata-ub-ph:build (dunka/master) $ ./dtest --test_fft
Testing Finished
Total number of individual testing statements executed: 7732
All tests completed successfully
Regards,
Duncan Palmer

Add MKL DFTI FFT bindings.

---

dlib/CMakeLists.txt

Problem: Visual Studio linker errors resulting from mixed /MT and /MD settings
Solution: don't set CUDA_PROPAGATE_HOST_FLAGS to OFF when using Visual Studio

Fix Visual Studio build by not setting CUDA_PROPAGATE_HOST_FLAGS to OFF

---

dlib/test/string.cpp

Hi,
the current test cases for the `split` method use wide-strings, but a test case e.g. for unicode non-breaking space is missing.
So this PR introduces a new test case for a unicode non-breaking space delimiter and uses some (German) umlauts in the text to be splitted.

Added new test case for split method (unicode non-breaking space)

---

setup.py

Since `cmake` is not able to find Python-libraries under anaconda environment, 
`-DPYTHON_LIBRARY `and `-DPYTHON_INCLUDE_DIR` flags should be appended to `cmake` command with  respective folders.
I did this by appending them to `cmake_extra_arch`.

Modify setup.py so that it can be installed under conda environment

---

dlib/statistics/running_gradient.h
dlib/threads/thread_pool_extension.cpp
dlib/threads/thread_pool_extension.h

Fixed issue with uninitialised variables. There are 2 places where std::exception_ptr eptr is not initialised. One in the CPP and one in the header file of thread_pool_extension.

Fixed issue with uninitialised variables in thread_pool_extension. 

---

dlib/test/matrix2.cpp

Hi,
this patch makes the `matrix2` test case more robust on ARM64, see #392.
Patch was tested on an ODROID-C2 and PINE64 with Arch Linux. 
Fixes #392 :)

Fix for failing matrix2 test on ARM64

---

dlib/image_loader/jpeg_loader.cpp
dlib/image_loader/jpeg_loader.h

Addresses the issue mentioned in #406 , i.e. dlib reports an error when libjpeg-turbo successfully loads a 4-plane RGBA JPEG image.

add support for loading of RGBA JPEG images

---

dlib/CMakeLists.txt

This is one solution for getting dlib to build on Mac when both X11 and anaconda are installed. See #437 for more details. Tested on Mac with X11 and Anaconda installed.

Remove anaconda from X11_INCLUDE_DIR

---

dlib/filtering/kalman_filter.h
dlib/filtering/kalman_filter_abstract.h

Sometimes initial state is known, also sometimes the state should be corrected (like if the model has known boundaries).

add set_state to kalman filter for the case we know the initial state

---

dlib/cmake_utils/cmake_find_blas.txt

This will allow linking to OpenBLAS when compiling with MinGW.
For example, on my system OpenBLAS is located in d:\lib directory. And compiling this way:
```
cmake .. -G"MinGW Makefiles" -DCMAKE_PREFIX_PATH=d:\lib
```
gives me dlib compiled with OpenBLAS
This PR only modified one line and everything works. Do you prefer moving MINGW into separate if-branch of CMakeLists.txt for clearer code?

Allow MINGW OpenBLAS usage

---

dlib/image_processing/scan_fhog_pyramid.h

already cleared at the beginning

dets cleared twice in evaluate_detectors of scan_fhog_pyramid.h

---

dlib/CMakeLists.txt

There is a conflict between X11 and miniconda. The solution is the same as the one for anaconda.

remove miniconda

---

dlib/CMakeLists.txt

Wether asserts are enabled or not, is now only suggested by dlib, and not longer imposed. The user can override using SET(CACHE FORCE) or command line -DDLIB_ENABLE_ASSERT=ON/OFF anytime.
Apparently, vim stripped all of the trailing spaces as well. I suggest looking at the file here, if all the whitespace changes are too confusing.
https://github.com/mcourteaux/dlib/blob/master/dlib/CMakeLists.txt
(If you want I can make another pull request to strip a bunch of trailing spaces.)

Fix asserts, super clean!

---

dlib/test/optimization_test_functions.cpp

Hi Davis,
I am currently coding a module for automatic differentation that includes the evaluation of second-order derivatives. While coding and running the module's tests I found out that the module's automatic Hessian of Brown's function wasn't numerically equal to the one you provide in dlib's optimization tests. 
This PR corrects a typo, which generated an erroneus (1,1)-th entry of the Hessian:
```
16 INFO  [0] test.auto_diff_models: brown_hessian(p) = 
[131198 214816 -18521.3 -12455.7] 
[214816 451387 -28454 -18807.9] 
[-18521.3 -28454 49662.9 31984.8] 
[-12455.7 -18807.9 31984.8 27033.6]
16 INFO  [0] test.auto_diff_models: auto_diff_brown_hessian(p) = 
[131198 214816 -18521.3 -12455.7]
[214816 456304 -28454 -18807.9]
[-18521.3 -28454 49662.9 31984.8]
[-12455.7 -18807.9 31984.8 …
```

Corrected typo that generated an erroneus Hessian of Brown's function.

---

dlib/CMakeLists.txt
dlib/cmake_utils/dlib.pc.in

Hi @davisking 
1. I'd like to get the `GNUInstallDirs` module into dlib. It sets all install paths to the GNU coding standard defaults (i.e. what is currently the case) but allows for users to change them. Furthermore, this gets rid of the previous custom `LIB_INSTALL_DIR` solution, which is not idiomatic and unsupported by Kitware. The current solution using `GNUInstallDirs` is more generalisable and supported by Kitware.
2. Furthermore, I've removed the installing of the license file. Most distributions do not install license files as they are redundant (it is specified in package metadata). Also, what license a software is under is independent of whether the license is installed alongside it.

CMake improvements

---

dlib/simd/simd4f.h
dlib/simd/simd4i.h
dlib/simd/simd_check.h

This PR adds SIMD instructions support for ARM/NEON processors
Tested with Nvidia Tegra TK1. All face detection, some SVM and correlation tracker functions now will run faster on ARMs. My performance measurements are in #557. 
All code tested with dtest --runall on TK1 and rechecked on Windows machine with MinGW 6.2 in AVX and SSE2 modes.
NEON is not enabled by default in G++ compiler on ARM platfortm. To enable it, pass "-mfpu=neon" flag to compiler
`cmake .. -DCMAKE_CXX_FLAGS="-mfpu=neon"`

ARM NEON SIMD support

---

dlib/matrix/matrix_blas_bindings.h
dlib/matrix/matrix_trsm.h

This PR is to fix issue #570. C style enum keywords in function declarations are removed in matrix_blas_bindings.h and matrix_trsm.h to avoid conflicts with declaration in cblas library API on Ubuntu.

remove enum in function signature to avoid cblas declaration conflicts

---

appveyor.yml

I've created a simple AppVeyor config for building the test and examples on Windows. The test is actually run, although I find them a little bit unstable - they sometimes fail.. e.g: https://ci.appveyor.com/project/andyli/dlib/build/5
Anyway, that can be improved separately later by e.g. having a fixed random seed.
Before merging this, please head to https://ci.appveyor.com, add this repo as a project.
You probably want to enable "Skip branches without appveyor.yml" in project setting.

Appveyor for Windows CI

---

dlib/gui_core/gui_core_kernel_1.cpp
dlib/gui_core/gui_core_kernel_1.h
dlib/gui_core/gui_core_kernel_2.cpp
dlib/gui_widgets/base_widgets.cpp
dlib/gui_widgets/base_widgets.h
dlib/gui_widgets/drawable.h
dlib/gui_widgets/fonts.cpp
dlib/gui_widgets/fonts.h
dlib/gui_widgets/nativefont.h
dlib/gui_widgets/widgets.cpp
dlib/gui_widgets/widgets.h
dlib/iosockstream/iosockstream.h
dlib/smart_pointers_thread_safe.h
dlib/sockets/sockets_kernel_1.h
dlib/test/gui/main.cpp
dlib/threads/thread_pool_extension.h
dlib/timer/timer.cpp
dlib/timer/timer.h

In an effort to make DLib compilable under C++17 shared_ptr_thread_safe is replaced with std::shared_ptr. See #586 and #588

Replace shared_ptr_thread_safe with std::shared_ptr

---

dlib/geometry/vector.h

C++17 mandates deletion of inheritance-style traits from standard lib.
These are replaced with explicit typedefs

Change type traits from inherited to explicit

---

dlib/test/elastic_net.cpp

Noticed compiler warning `C4800: 'double': forcing value to bool 'true' or 'false' (performance warning)`.
Suggesting to change the test to what perhaps was the original intention.

Suggesting to fix possible parenthesis issue in elastic net test

---

dlib/dnn/trainer.h

Fix one bug in trainer that cause crash when using multi GPUs and loss increased. The details see https://github.com/davisking/dlib/issues/614.

Reinitialize averagers when saved sync file was reloaded.

---

dlib/dnn.h

**Problem:** Visual Studio's `vcpkgsrv.exe` constantly uses a single CPU core, apparently never finishing whatever it's trying to do. Moreover, this issue prevents some operations like switching from Debug to Release (and vice versa) in the IDE. (Your mileage may vary.)
**Workaround:** Keep manually killing the `vcpkgsrv.exe` process.
**Solution:** Disable IntelliSense for some files. Which files? Unfortunately this seems to be a trial-and-error process.
NB: Visual Studio needs to be restarted for this fix to help. (Otherwise `vcpkgsrv.exe` keeps on popping up.)

Problem: Visual Studio's vcpkgsrv.exe constantly uses a single CPU core

---

dlib/dnn.h
dlib/test/dnn.cpp

Disable IntelliSense even for the local ResNet declarations in the DNN tests.
(See #666.)

Disable IntelliSense for all DNN unit tests

---

dlib/dnn/loss.h
dlib/dnn/loss_abstract.h
dlib/test/dnn.cpp

Add new loss for arbitrarily weighted pixel inputs. May be useful e.g. to emphasize rare classes.
I don't know if this is interesting to anyone but myself. If this is a candidate to be merged, then I can add some test case and an entry to `loss_abstract.h`. If not, then the PR can well be closed – won't be a problem for me.

Add new loss for weighted pixel inputs

---

dlib/dnn/cuda_data_ptr.h
dlib/dnn/cudnn_dlibapi.cpp
dlib/dnn/cudnn_dlibapi.h

This PR makes convolution layers in GPU mode to share workspace memory buffers. This leads to significant memory usage decrease with fast convolution algorithms
Existing dlib implementation of large networks (Resnet34) is using "prefer_smallest" cuDNN convolution algorithms to make it process large batches with same GPU RAM.
With this PR we are now able to use fast convolution algorithm with near the same RAM usage (about 100 Mb additional RAM required)
I have tested it with GTX TitanX (Maxwell/12GB) and GTX 1080 Ti (Pascal/11GB). TitanX is now able to train imagenet with batch size = 160 with fast algorithms (same batch size as smallest algorithms), and 1080 is able to train batch_size = 155
Training time:   
* TitanX, smallest - 1.6 second per batch of 160 images
* TitanX, fast  - 0.9 …

cuDNN convolution algorithms shared workspace

---

dlib/general_hash/random_hashing.h

The non-standard dash character confuses Microsoft compiler and produces warnings like 'The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss' when compiled on non-Latin system locale codepages

Fix strange dash in Box-Muller

---

python_examples/cnn_face_detector.py
tools/python/CMakeLists.txt
tools/python/src/cnn_face_detector.cpp
tools/python/src/dlib.cpp

This PR adds a simple wrapper for calling the cnn face detector from python. With this, you can now use the cnn face detector in python just like the face HOG detector:
```python
import dlib
cnn_face_detection_model = dlib.cnn_face_detection_model_v1("mmod_human_face_detector.dat")
dets = cnn_face_detection_model.cnn_face_detector(img, 1)
for i, d in enumerate(dets):
print("Detection {}: Left: {} Top: {} Right: {} Bottom: {}".format(i, d.left(), d.top(), d.right(), d.bottom()))
```
It seems to work fine, but I haven't written C++ code in a long time and I'm not very experienced with C++11 and the dlib code base. So all feedback is very welcome (including "this sucks, try again").
Thanks!

Add a python wrapper for the cnn face detector

---

dlib/CMakeLists.txt

PNG_LIBRARY set by libpng's FindPNG.cmake does not contain zlib dependancy.  This causes the CHECK_FUNCTION_EXISTS(png_create_read_struct LIBPNG_IS_GOOD) to fail with liner errors, and for dlib to use it's internal copy of PNG.
Updated to use libpng's PNG_LIBRARIES variable.  This also sets both PNG and ZLib libraries in dlib_needed_libraries.

Pull in external libpng dependencies properly

---

dlib/CMakeLists.txt
dlib/cmake_utils/use_cpp_11.cmake

This PR makes pussible compilation with Clang on Windows platform. I have tried Clang 5.0, it has full support of C++11, it is compatible with all MSVC libraries (MKL) and it supports CUDA and compiled code is faster than original MSVC-generated code
So I think, users of Dlib who need CUDA on Windows platform for DNN can easily do it with Clang
To use Clang after installation, you need to pass this arguments to CMAKE:
```
cmake ..  -G"Visual Studio 14 2015 Win64" -T"LLVM-vs2014"
```
There is one annoying warning during compilation
```
warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument]
```
But I can't find way to disable it. -Wno-unused-command-line-argument does not help, -Qunused-argument does not help too

Clang support for Windows

---

dlib/image_processing/full_object_detection.h
python_examples/cnn_face_detector.py
tools/python/src/cnn_face_detector.cpp

Small improvements to cnn face detection python interface
changes:
- can use the detector in two modes:
* single image mode - returns a mmod_rectangles object
* list of images - returns a batch_mmod_rectangles object
- this mode can be used for speed when CUDA is activated
- if CUDA is deactivated then there is no real speed advantage when comparing the two
- mmod_rect object: contains a rectangle object and a confidence score for the detection
- mmod_rectangles: represents all detections in an image, can be iterated over as a list
- batch_mmod_rectangles: represents all detections over a list of images, can be iterated over as a 2d list

improvements to cnn face detection python interface

---

dlib/CMakeLists.txt
dlib/cmake_utils/use_cpp_11.cmake

This PR fixes the compilation of examples with Clang + CUDA + Windows. There will be a lot of warnings, but compilation of dnn_mmod_exx is successul

hotfix static runtime in cuda with clang and windows

---

dlib/dnn/loss.h

Extract this fix from #812, to be handled separately.

MMOD: fix loss from ignored rects when using loss_per_missed_target != 1

---

python_examples/face_clustering.py
tools/python/src/face_recognition.cpp

Exposed more functionality from the C++ API in the Python API:
1. Exposed the save_image_chip and save_image_chips to save a 150x150 px file with 0.25 padding which is suitable to be loaded and jittered in the dnn_metric_learning_on_images_ex.cpp
2. Added a cluster method which accepts a list of descriptors and returns a list containing integers identifying the cluster label for each descriptor.
3. Added a python example which can be pointed at a folder containing images of a common person photographed along with other different people. The example then performs clustering and saves the extracted faces (assuming the common face will form the biggest cluster) to a specified folder.

Added face clustering example to Python API

---

dlib/dnn/trainer.h
dlib/dnn/trainer_abstract.h

Add get_net parameter that allows to call the function without forcing flush to disk

---

dlib/dnn/layers.h

Hi,
I should be wrong, but I got some errors when trying to use an add_prev layer with a mmod loss.
I fixed it and hope it could be usefull for someone else.
Regards,
Gilles Rochefort.
PS:
Following is a small snippet of the errors I got
> In file included from 3rdparty/dlib/dlib-src/dlib/../dlib/dnn/layers.h:15:
> 3rdparty/dlib/dlib-src/dlib/../dlib/dnn/utilities.h:218:41: error: no member named 'map_output_to_input'
>  in 'dlib::add_prev_<tag1>'
>                 p = net.layer_details().map_output_to_input(p);
>                     ~~~~~~~~~~~~~~~~~~~ ^

Missing interfaces in add_prev for compatibility with mmod loss.

---

dlib/opencv/cv_image.h
dlib/opencv/cv_image_abstract.h

Hi,
I designed a dnn using the mmod_loss and need to rely on a cv::Mat as input image. I may be wrong but when I tried to use the cv_image wrapper without extra copy, I got some errors about missing operators.
I fixed it, and it may be of interests for someone else.
Regards,
Gilles Rochefort
PS:
Here is a copy of the errors I got:
> In file included from 3rdparty/dlib/dlib-src/dlib/../dlib/dnn.h:13:
> 3rdparty/dlib/dlib-src/dlib/../dlib/dnn/input.h:622:33: error: type 'dlib::cv_image<dlib::bgr_pixel>' does not provide a call operator
>                         p[c] = (img(r,c).green-avg_green)/256.0;
>                                 ^~~
> 3rdparty/dlib/dlib-src/dlib/../dlib/dnn/input.h:632:33: error: type 'dlib::cv_image<dlib::bgr_pixel>' does not provide a call operator
> …

Add some operator() to cv_image for compatibility with mmod loss.

---

dlib/matrix/lapack/pbtrf.h
dlib/matrix/matrix_la.h
dlib/test/matrix.cpp

Hello, I have been using dlib for nonlinear optimisation with large numbers of variables. This works nicely - thank you! However in this case, the Cholesky factorization of the Hessian dominates the computation time as it scales as O(n^3). 
If the Hessian has a banded structure then it is possible to compute the factorisation in O(n\*n\*b) where b is the bandwidth. Since b << n, this can provide a considerable performance boost (\~300x in my case where n\~1500 and b\~3). 
This PR adds code to detect such banded Hessians and, if detected, uses a specialised Cholesky factorization routine. This detection step obviously imposes a small cost for non-banded matrices, however it should be negligible compared to the subsequent factorisation.

Use banded Cholesky factorization if possible

---

dlib/cmake_utils/cmake_find_blas.txt

On windows, it seems like the CMake build only looks for the Intel MKL versions of LAPACK and BLAS. This PR uses find_package to try and find LAPACK and BLAS. This is useful if you have installed these libraries via vcpkg, for example.

Win lapack

---

dlib/cmake_utils/dlibConfig.cmake.in

Currently, dlib hardcodes dlib_LIBRARIES in dlibConfig.cmake. This is not required as the library and dependencies will be picked up in a configuration dependent manner by dlib-{configuration}.cmake if dlib_LIBRARIES is set to dlib::dlib. The current approach means that different configurations (Release/Debug/...) cannot easily be installed side-by-side on Windows. 
This PR removes this hardcoded library path. I've tested that CMake successfully detects the library and dependencies on Windows 7 and macOS.

Remove explicit specification of library path in dlibConfig.cmake

---

dlib/matrix/matrix_op.h

Doesn't add anything, just makes my compilation way calmer :)

pedantic: fix "extra `;`" warnings when compiling with -Wpedantic

---

dlib/dnn/loss.h
dlib/dnn/loss_abstract.h
examples/dnn_mmod_find_cars_ex.cpp

**What**
I want to train MMOD based detectors that are _not_ scale-invariant. So I am not even going to use an image pyramid.
How come? Think of detecting vehicles in satellite images, for example. There is essentially no perspective, and all cars and trucks are pretty much the same size. Now it would be silly to report a sedan that is 50 cm or 50 m long, for example – even if there is something in the image that, when scale is ignored, looks a lot like a sedan.
In fact it would be silly to even look for a sedan that is 50 cm or 50 m long. So bypassing the image pyramid should also make the detector run faster, when invariance to scale is not needed.
However, I still want my detector to understand different object sizes. (For example, to have separate detector windows for small trucks and …

Add support for non-scale-invariant MMOD

---

dlib/gui_widgets/widgets.cpp
dlib/gui_widgets/widgets.h

This pull request adds a few lines to provide a getter for the selected tab in a tabbed_display.
In [`dlib/gui_widgets/widgets_abstract.h:1115`](https://github.com/davisking/dlib/blob/acda88a5e3ec51e0880a15683fb75e07d8145261/dlib/gui_widgets/widgets_abstract.h#L1115) there is a getter for the currently selected tab in a tabbed_display. However, `widgets.h` and `widget.cpp` missed this, which I figured out when my code wouldn't link properly. 
Out of curiosity, what is the reason to have basically two almost identical header definitions of the tabbed_display, one in `widgets.h` and one in `widgets_abstract.h`? The latter seems not to be picked up by the compiler (without my changes in `widgets.h` the new function wouldn't compile) and seems to be there mostly for the documentation purpose?

Adding missing implementation of tabbed_display::selected_tab

---

tools/imglab/src/metadata_editor.cpp

Less hand movement from <TAB> position to arrow keys - this helps me annotate faster.

imglab: select next/previous image with 's' and 'w'

---

dlib/opencv/to_open_cv.h

Prevent trying to send aggregate to cv::DataType when converting an image to opencv.
```
In file included from /home/pi/git/dlib/dlib/../dlib/opencv.h:11:0,
from /home/pi/git/FaceLibraries/FaceService/src/FaceService.cpp:21:
/home/pi/git/dlib/dlib/../dlib/opencv/to_open_cv.h: In instantiation of ‘cv::Mat dlib::toMat(image_type&) [with image_type = dlib::matrix<dlib::rgb_pixel>]’:
/home/pi/git/FaceLibraries/FaceService/src/FaceService.cpp:299:42:   required from here
/home/pi/git/dlib/dlib/../dlib/opencv/to_open_cv.h:29:24: error: ‘type’ is not a member of ‘cv::DataType<dlib::rgb_pixel>’
return cv::Mat(num_rows(img), num_columns(img), cv::DataType<type>::type, image_data(img), width_step(img));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```

Fixed type passing to opencv to use basic instead of aggregate.

---

dlib/dir_nav/dir_nav_kernel_2.cpp
dlib/dir_nav/dir_nav_kernel_2.h

see: https://stackoverflow.com/a/18284105
tested: clang-3.9, clang-5.0
Error:
```
/Source/dlib/dir_nav/dir_nav_kernel_2.h:397:31: error: no viable overloaded '+='
last_modified += std::chrono::nanoseconds(buffer.st_atim.tv_nsec);
~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/chrono:782:43: note: candidate function not viable: no known conversion from 'duration<[...], ratio<[...], 1000000000>>' to 'const duration<[...], ratio<[...], 1000000>>' for 1st argument
_LIBCPP_INLINE_VISIBILITY time_point& operator+=(const duration& __d) {__d_ += __d; return *this;}
^
Source/dlib/dir_nav/dir_nav_kernel_2.cpp:69:33: error: no viable overloaded '+='
state.last_modified += std::chrono::nanoseconds(buffer.st_atim.tv_nsec);
~~~~~~~~~~~~~~~~~~~ ^ …
```

add chrono::duration_cast<>() cast for clang error

---

dlib/cmake_utils/set_compiler_specific_options.cmake

On systems such as FreeBSD, `uname -p` returns amd64 (in lowercase) and `-DUSE_AVX_INSTRUCTIONS=1` does not work (the option is ignored).

Make sure intel architecture is properly detected

---

dlib/simd/simd8f.h
dlib/simd/simd8i.h

avoid excessive copying of simd4f structs by making low() & high() methods of simd8f struct return "const simd4f&"

>2x performance increase if DLIB_DO_NOT_USE_SIMD is defined

---

examples/dnn_mmod_train_find_cars_ex.cpp

I found a typo in dnn mmod train find cars example:
```"is there a care here?"``` which should be ```"is there a car here?"```

fix typo in dnn mmod train find cars example

---

dlib/cmake_utils/test_for_cuda/CMakeLists.txt
dlib/cmake_utils/test_for_cudnn/CMakeLists.txt

Set `CUDA_PROPAGATE_HOST_FLAGS=OFF` in FindCUDA.cmake to avoid duplicate flag errors in nvcc that can occur when host flag forwarding is enabled and `-std=c++11` is set in `CMAKE_CXX_FLAGS` in the active toolchain.
```
option(CUDA_PROPAGATE_HOST_FLAGS "Propage C/CXX_FLAGS and friends to the host compiler via -Xcompile" OFF)
```
This is a follow up to #674 and seems to be the simplest way of avoiding the problem.  It is related to this issue https://gitlab.kitware.com/cmake/cmake/merge_requests/1628, which includes a minimal test case.  I realized this is unlikely to occur if one isn't using a toolchain w/ `-std=c++11` for the build.  The only caveat I can see with this solution, is if one needs to cross compile for CUDA somehow in the future, or toolchain flags are needed for the CUDA …

CUDA_PROPAGATE_HOST_FLAGS=OFF in FindCUDA.cmake for try_compile tests

---

dlib/cmake_utils/cmake_find_blas.txt

First @davisking thanks for the great work!  Second, here's a very small contribution for macOS.
This PR will allow cmake to find MKL on macOS (solves #1033).
Basically the problem occurs because (at least based on the latest version of MKL`INTEL_MKL_VERSION 20180001`) the directory layout differs between Linux and macOS (see appendix below).
This change just tells the script to look in the right place for macOS.
As an aside, to use MKL on macOS you must have your LD_LIBRARY_PATH set to include both the mkl lib search path _and_ the intel lib search path (to find intel's openmp5 libs).   For example, before running a dlib example run:
```
export LD_LIBRARY_PATH=/opt/intel/lib/:/opt/intel/mkl/lib/
```
Appendix:
macOS MKL installation:
```
me@macOS:~$ tree /opt/intel/mkl/lib/ …
```

Add support for finding MKL on macOS w/ cmake, Fixes #1033.

---

tools/python/src/svm_c_trainer.cpp
tools/python/test/test_svm_c_trainer.py

This PR exposes the `rvm_trainer` class to Python. Additionally, all trainers are provided with an `init()` function.
I am not sure if the `rvm_trainer<linear_kernel<sample_type> >` and `rvm_trainer<sparse_linear_kernel<sparse_vect> >` classes are correct, since there does not exist an rvm counterpart of the `svm_c_linear_trainer` class.

Add Python rvm_trainer and init functions

---

tools/python/src/global_optimization.cpp
tools/python/test/test_global_optimization.py

Example calls that are made to work with this PR:
* `find_max_global(lambda *args: sum(args), [0, 0, 0], [1, 1, 1], 10)`
* `find_max_global(lambda a, b, *args: a+b+sum(args), [0, 0, 0], [1, 1, 1], 10)`
This call is still disallowed, because the function being optimized requires too many arguments:
* ~~`find_max_global(lambda a, b, c, d, *args: a+b+c+d+sum(args), [0, 0, 0], [1, 1, 1], 10)`~~

Added support for variadic Python functions in find_max_global.

---

dlib/dnn/cpu_dlib.cpp
dlib/dnn/tensor.h
dlib/dnn/tensor_abstract.h

Like #1148, but for `tensor` only.

Change types of tensor's size-related members to prevent integer overflow

---

CMakeLists.txt
dlib/CMakeLists.txt

This PR removes the dlib-shared CMake target and also causes the dlib CMake target to be either a shared or static library depending on the state of CMake's BUILD_SHARED_LIBS variable. Currently, the dlib target is always a static library.
There has been some discussion about this already: https://github.com/davisking/dlib/issues/923, @SoapGentoo, @xsacha, https://github.com/davisking/dlib/issues/1137, @kimwalisch.
This PR addresses some of the issues.  However, it isn't perfect. Here is one problematic case: Someone builds their own library via cmake and uses `add_subdirectory(dlib)` to add dlib as a dependency. They then set `BUILD_SHARED_LIBS=1` so that their library (and now dlib as well) are built as shared libraries. They then do `make install`, but since dlib's cmake files don't …

Only define one dlib target in CMake and shared vs. static is determined by BUILD_SHARED_LIBS variable.

---

dlib/serialize.h

Set istream flags to 0 in old_deserialize_floating_point.  This was flagged by [[nodiscard]] warning in MS compiler.

Clear flags

---

python_examples/train_object_detector.py

That's pretty much it, there was an unnecessary semicolon in the `train_object_detector.py` python example.

Remove unnecessary semicolon

---

dlib/assert.h
dlib/matrix/matrix_assign.h

This prevents name clashes when working with boost.
This happed to us after updateing from boost 1.58 to 1.67.

Renamed BOOST_JOIN to DLIB_BOOST_JOIN 

---

dlib/image_loader/image_loader.h

Rows in bitmap image file can be arranged either top-down, or bottom-up. Current implementation of BMP file reader in dlib supports only top-down row arrangement.
Fix: negative `biHeight` value (from DIB) means that we have a bottom-up arrangement. Therefore rows are assigned to an image in a reverse order.
- [Top-Down vs. Bottom-Up DIBs](https://msdn.microsoft.com/en-us/library/windows/desktop/dd407212(v=vs.85).aspx) by Microsoft

Supporting bottom-up DIBs

---

dlib/array/array_kernel.h
dlib/image_transforms/interpolation.h

Hello Davis,
This PR is about parallelizing `add_image_rotations` which takes an unreasonable amount of time on my machine, while there are a lot of idling CPUs.
I'm not sure about some low level arbitrary choices I've made and implementation details, so please, get back to me. I'll remove the debug prints and all that while treating your feedback.
Many thanks!

parallelize image rotations

---

dlib/CMakeLists.txt

Add a default cpack "package" target when dlib is directly built, as an alternative to building for immediate installation.

Add a default cpack "package" target.

---

dlib/image_loader/image_loader.h

The 'long' type can be 32 bits or 64 bits depending on what compiler you are using (LLP64 vs LP64). If the long type is 64 bits the biHeight variable will receive a very big number when the bmp image height is negative, causing a std::bad_alloc exception when calling the 'image.set_size' method.
I think that would be a good idea to replace all numeric types with the ones declared in \<cstdint\>(C++11) and get rid of "../uintn.h".

Fix bad_alloc exception when loading bmp images with negative height

---

dlib/image_loader/image_loader.h

The 4 bytes starting from the 0x06 offset of a bmp file are marked as 'Reserved' but it doesn't guarantee that these bytes are zeroed, some applications uses this area for its own purposes and the output file
still a valid bmp file.

Ignore bmp reserved area

---

dlib/console_progress_indicator.h

With C++17 enabled on VS15.6+, this triggered a nodiscard warning which led to failed builds when warnings as errors is enabled.

Remove redundant line

---

dlib/geometry/drectangle.h
dlib/geometry/drectangle_abstract.h
dlib/geometry/rectangle.h
dlib/geometry/rectangle_abstract.h
tools/python/src/image2.cpp
tools/python/src/rectangles.cpp

Added a python function `scale_image` that uses dlib `resize_image` to do scaling. Not sure if this is OK as its own function or rather should just be another signature of `resize_image` binding?
I often have to down scale large images in order to fit into graphics memory for cnn face detection but then want to use the original full size image for pose prediction. I have added `scale_rect` for rectangle and drectangle which accepts a scale factor so that the detected face rect can be rescaled back to fit the face in the original full size image.

Python Image and Rectangle Scaling

---

dlib/cuda/gpu_data.cpp

resolves #1513
Candidate solution: busy-loop until `cudaStreamQuery` returns `cudaSuccess`

Apparently fix #1513 by avoiding the cudaStreamSynchronize call

---

dlib/CMakeLists.txt

When using dlib as explain in examples/CMakeLists.txt, from a CMake project with cmake minimum required version >= 3.0, this warning is displayed:  
```
CMake Warning (dev) at /home/facug91/dlib/dlib/CMakeLists.txt:9 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
PROJECT_VERSION
PROJECT_VERSION_MAJOR
PROJECT_VERSION_MINOR
This warning is for project developers.  Use -Wno-dev to suppress it.
```
As dlib uses it's own version variables, there's no need to use version in the project command, so simple setting this policy to NEW avoids the warnings (and setting it to OLD is …

Set CMake policy CMP0048 to NEW when available.

---

dlib/cmake_utils/find_blas.cmake

Issue #787 was closed, because no PR was made, but the bug in the CMake remained.  
The problem was that on Windows, CMake script was not looking up for mkl headers path. I've just added quite the same code used on UNIX, with different hint paths.
I need this for the tracker module, and there's where I've tried it. I've also compiled and run all tests.
Anyway, there was a test that failed, but it doesn't seem to have anything to do with this change. This is the exact error message:  
```
Error occurred at line 108.  
Error occurred in file c:\dlib\dlib\test\is_same_object.cpp.  
Failing expression was is_same_object(a,b) == false.  
```

Fix #787: find MKL FFT with CMake on Windows

---

dlib/CMakeLists.txt
dlib/cmake_utils/find_blas.cmake

MKL can be used with TBB for multithreading, instead of OpenMP.  
In this PR I add an option to CMake to link to these libraries, by default in OFF to maintain current behavior.  
I've performed a few tests by my own, but I haven't used a powerful machine, where the difference can be higher. I've trained some DNNs (a specific number of epochs only, because it takes too long to finish training on CPU), and on Ubuntu 18.04 seems to be ~8% slower using TBB, while on Windows 10 seems to be the opposite, ~14% faster or even more.  
I wanted to ask you Davis if there're some kind of test you think would be better to benchmark this.

Add MKL with TBB support to CMake

---

dlib/dnn/layers.h
dlib/matrix/matrix_utilities.h
dlib/matrix/matrix_utilities_abstract.h
dlib/test/matrix.cpp
dlib/test/matrix2.cpp

As discussed in issue #1579, there was no function on dlib to perform pointwise division of matrices.  
This PR adds that function and corresponding unit tests.  
Here are some performance tests I've ran, all of them performing a pointwise division. The number at the end is the number of arguments used for each test.  
With a matrix of size 2016x1512
pointwise_multiply2           17 ms  
pointwise_multiply3           20 ms   
pointwise_multiply4           23 ms   
pointwise_division2           15 ms   
pointwise_division3           18 ms   
pointwise_division4           22 ms   
With a matrix of size 4032x3024
pointwise_multiply2           70 ms   
pointwise_multiply3           81 ms   
pointwise_multiply4           92 ms   
pointwise_division2           62 ms   
pointwise_division3 …

Add pointwise_divide function

---

dlib/external/libjpeg/jdhuff.cpp

the register storage specifier was deprecated in C++11 and removed in C++17.
The presence of `register` prevents `dlib` from compiling against the C++17 standard.

remove register keyword from jdhuff for C++17

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/test/dnn.cpp
examples/dnn_semantic_segmentation_ex.cpp
examples/dnn_semantic_segmentation_ex.h
examples/dnn_semantic_segmentation_train_ex.cpp

To address the [recent interest](https://github.com/davisking/dlib/issues/1236#issuecomment-447581865) in a U-net implementation, this PR adds a possibly-useful `resize_to_prev` layer, and upgrades the semantic-segmentation example.
Compared to the corresponding network without skip connections (see #943), the updated example should be able to draw more details:
However, overall it's not too much more accurate on the PASCAL VOC 2012 data -- this time around, the training should finish like this (note the lower loss but not much better accuracy, when compared to numbers reported in #943):
```
step#: 117901  learning rate: 0.001  average loss: 0.0239372    steps without apparent progress: 4941
step#: 118018  learning rate: 0.001  average loss: 0.0238844    steps without apparent progress: …
```

Add U-net style skip connections to the semantic-segmentation example

---

dlib/simd/simd_check.h

ECX must be set to 0 to read this flag, the easiest way to achieve this
is to use __cpuid_count with 0 as the second argument.
---
I have been repeatedly getting the message "Dlib was compiled to use AVX2 instructions, but these aren't available on your machine." despite using a Ryzen processor with AVX2.
This change stops the message appearing for me. I haven't found a primary source for it but several mentions e.g.
https://bugs.chromium.org/p/chromium/issues/detail?id=630077#c9

Reliably detect AVX2 at runtime on Linux

---

dlib/cuda/gpu_data.cpp

As [it seems](https://github.com/davisking/dlib/issues/1513#issuecomment-447716981) that #1513 may occur also outside Windows (e.g., RHEL 7), make the #1514 fix apply on other platforms as well.

Apply the #1514 fix even on non-Windows platforms, and change all remaining cudaStreamSynchronize calls

---

dlib/cuda/gpu_data.cpp

I noticed I was still hitting #1513, although this time on GTX 1080 Ti (CUDA 10, Windows 10, MSVC 2017).
Then I realized that #1514 wasn't helping, in particular after #1596, because `CUDA_VERSION` wasn't even `#define`d here!
I actually thought that the preprocessor would give an error in this case, but [apparently that is not the case](https://stackoverflow.com/questions/17160755/is-there-a-way-to-both-check-a-macro-is-defined-and-it-equals-a-certain-value-at). Learn something new every day!

Make sure CUDA_VERSION is defined

---

python_examples/face_recognition.py
tools/python/src/face_recognition.cpp

At present the python api requires to pass an image  as well as face detection info. There are use cases where the aligned images are already prepared and what is needed to generate the embeddings for them. 
This additional api expects the input image to be of size 150x150 and bring the python api for face recognition at par with that of C++ for inference needs.

Add python api that generates desciptor(s) from the aligned image(s)

---

dlib/cuda/gpu_data.cpp

When upgrading to CUDA 10.1, I've started to have the same problem fixed in #1514.  
This is because the CUDA_VERSION wasn't change in gpu_data.cpp file.  
This pull request simply upgrades version check from 10000 to 10010 (CUDA_VERSION in CUDA 10.1).

Change CUDA version check for cudaSync from 10000 to 10010

---

dlib/matrix/lapack/gees.h
dlib/matrix/lapack/geev.h
dlib/matrix/lapack/geqrf.h
dlib/matrix/lapack/getrf.h
dlib/matrix/lapack/ormqr.h
dlib/matrix/lapack/pbtrf.h
dlib/matrix/lapack/potrf.h
dlib/matrix/lapack/syev.h
dlib/matrix/lapack/syevr.h

This brings const correctness for lapack function parameters, according to the documentation provided by netlib.
~~I was not sure about code formatting and west const/east const, because I found some mixed styles. For the latter, I decided to keep all the changes with east const. Anyway, if you want me to format the code in a different way, it is not a problem.~~ I changed the format style using the _west const_ following the suggestion of @davisking.
P.s.: ironically, I sent a similar patch to armadillo because some lapack functions in dlib were const correct and it created some conflicts armadillo declarations. Now that the patch is in trunk and there is a release candidate, I noticed that exact same problem for dlib.

Fixed constness for lapack function declarations

---

dlib/global_optimization/global_function_search.cpp
dlib/matrix/matrix_math_functions.h

Just a pull request to silence some -Wpedantic warnings when compiling with g++ 8.3.0.
I was also wondering if it would be OK to remove that `DLIB_CASSERT`, since `num` is declared as a `size_t`.
```
[37/59] Building CXX object dlib/CMakeFi...ptimization/global_function_search.cpp.o
In file included from ../dlib/global_optimization/../matrix/../algs.h:111,
from ../dlib/global_optimization/../matrix/matrix_exp.h:6,
from ../dlib/global_optimization/../matrix/matrix.h:6,
from ../dlib/global_optimization/../matrix.h:6,
from ../dlib/global_optimization/global_function_search.h:8,
from ../dlib/global_optimization/global_function_search.cpp:2:
../dlib/global_optimization/global_function_search.cpp: In member function ‘void dlib::global_function_search::set_monte_carlo_upper_bound_sample_num(size_ …
```

fix some pedantic warnings

---

dlib/dnn/layers.h
dlib/dnn/utilities.h

These warnings occurred when building the semantic segmentation examples
Sorry for all this noise, I don't know if this bothers you, maybe I should wait a bit more before creating the pull request...
I build with these extra warnings: `-Wall -Wextra -Wpedantic -std=gnu++17`.
If if I don't enable the gnu extensions I get some weird warnings about variadic arguments in macros.

Even more warning silencing

---

dlib/general_hash/murmur_hash3.h

because the [[fallthrough]] warning protection is not valid before and ti keeps flooding the console with the following warning:
general_hash/murmur_hash3.h:28:26: warning: attributes at the beginning of statement are ignored [-Wattributes]
#define DLIB_FALLTHROUGH [[fallthrough]]
^
C:/Utilisateurs/A134883/Workspace/Perso/dlib/dlib/general_hash/murmur_hash3.h:224:21: note: in expansion of macro 'DLIB_FALLTHROUGH'
DLIB_FALLTHROUGH; // fall through

Ensures DLIB_FALLTHROUGH macro is only set for GCC>=7

---

dlib/dnn/input.h
dlib/dnn/input_abstract.h

Issue #354  
I'm doing some test with it, I'll be uploading a performance comparison tomorrow using it in the mmod (the training takes several hours).  
In the meantime I wanted to create the pull request, to be sure it's a good contribution, and to start reviewing the code.

Add input_grayscale_image_pyramid, issue #354

---

tools/python/src/vector.cpp
tools/python/test/test_point.py

* Add test to reproduce issue #1794 
* Fix python bindings

 Fix setting a point's y coordinate changes x instead (Python bindings)

---

dlib/external/pybind11/tools/FindPythonLibsNew.cmake

When dlib is compiling, cmake will compare python architecture and target
architecture. So in cross-compiling case, it is irrevelant because host and
target architecture often differs. The main problem come from checking python
architecture on host and not on target.
Here is an error when compiling dlib from x86_64 to arm 32-bit target :
```
Python config failure: Python is 64-bit, chosen compiler is 32-bit
```
So :
- Skipping the comparation when cross-compiling is enabled.
Signed-off-by: Romain Naour <romain.naour@smile.fr>
Signed-off-by: Alexandre PAYEN <alexandre.payen@smile.fr>

pybind11: cmake: ignore the check between host-python and cross-compiler

---

dlib/image_processing/generic_image.h

there was no actual harm here: the unconsting was consted up by the member (but it needn't have been had the member been pointer to non-const). 
generally speaking, `reinterpret_cast` is better than C-style casting because it cannot cast away constness.

don't cast away constness

---

dlib/dnn/loss.h

To address the possible issue mentioned [here](https://github.com/davisking/dlib/commit/29db3ee566d68b3a197e24394c3beb64513ca98e#r34900715), clear the `truth_idxs` vector between samples.

Clear truth_idxs between samples

---

dlib/dnn/loss.h
dlib/test/dnn.cpp

Ignore truth rects that overlap too much (have same index in feature coordinates)

---

dlib/dnn/loss.h

Since the `truth_idxs` might hold negative values, it should be declared as a `std::vector<int>` instead of `std::vector<size_t>`

fix signed/unsigned warning

---

dlib/dnn/loss.h
dlib/dnn/trainer.h
dlib/image_transforms/interpolation.h
dlib/pixel.h
examples/dnn_instance_segmentation_ex.cpp
examples/dnn_instance_segmentation_ex.h
examples/dnn_instance_segmentation_train_ex.cpp
examples/dnn_semantic_segmentation_ex.h
examples/dnn_semantic_segmentation_train_ex.cpp
examples/pascal_voc_2012.h

(resolves #1646)
This PR adds an _instance segmentation_ example.
In the sample images below, colors of rectangles depend on class, whereas segmentation colors are random (to show where one instance changes to another).
Some examples from the training set (PASCAL VOC 2012, but with bicycles, cars and cats only):
Some examples not seen during training:
(Yes, these is certainly overfitting, for example in the cat detector. But avoiding that is not really the point of this PR.)
The proposed implementation is (I guess) pretty much the simplest possible approach: first run standard MMOD object detector, then predict the correct segmentation mask for each found object. So object detection and segmentation are decoupled (separate networks).
An alternative approach would be a single loss layer, …

Instance segmentation

---

dlib/statistics/statistics_abstract.h

I've just noticed that the `vector_normalizer` documentation mentions the PCA, which only applies to `vector_normalizer_pca`, so I deleted that part of the documentation.

Fix vector normalizer doc

---

dlib/dnn/utilities.h
dlib/dnn/utilities_abstract.h

I've just added a simple visitor to count the parameters of a network.
Results for a ResNet 50:
- dlib:
``` c++
count_parameters(net);  // 22803176
```
- pytorch: 
``` python
sum(p.numel() for p in model.parameters() if p.requires_grad)  # 25557032
```
- keras
``` python
model.count_params()  # 25636712
```
There are some discrepancies, I think I'm doing it right, according to the `visit_layer_parameters` documentation and my ResNet 50 implementation.

add visitor to count net parameters

---

dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/dnn/loss.h
dlib/dnn/loss_abstract.h
dlib/test/dnn.cpp
examples/dnn_instance_segmentation_ex.cpp
examples/dnn_instance_segmentation_ex.h
examples/dnn_instance_segmentation_train_ex.cpp

- Add new loss layer for binary loss per pixel (say, for completeness)
- In the instance-segmentation example, resolve possibly overlapping instances using the per-pixel output intensity (and not result rect size as previously); while at it, also make the instance output look "soft":

 Add new loss layer for binary loss per pixel

---

dlib/CMakeLists.txt

Dlib does not use nsl symbols, why was this necessary ?
This make conda-forge build fail

Do not link to libnsl

---

dlib/image_transforms/interpolation.h

I want to extract image chips using nearest-neighbor interpolation, for segmentation masks and such. (A bicycle still isn't halfway between an aeroplane and a bird.)

If nearest-neighbor interpolation is wanted, then don't use an image pyramid

---

dlib/gui_widgets/widgets.cpp
dlib/gui_widgets/widgets.h
tools/imglab/src/cluster.cpp
tools/imglab/src/main.cpp
tools/imglab/src/metadata_editor.cpp

Using chinese whispers for "automatic" clustering usually works and is nice for lazy people, and scrolling to zoom is a bit annoying at least for me.
In case the diff isn't clear, I just moved the zoom handling code out from the on_wheel_{up,down} into separate functions and call those as appropriate instead.

imglab: chinese ("automatic") clustering, keyboard shortcuts for zooming

---

examples/dnn_introduction3_ex.cpp
examples/resnet.h

I realized that I was using the template parameter for `bn_con` and `affine` twice: once for the struct template and one for each template that needed a batch normalization layer inside the struct.
Now everything uses the top level template parameter, leading to more readable code :)

simplify resnet definition by reusing struct template parameter

---

dlib/serialize.h

An exception will be thrown if the actual size is larger than the limit of uint32 but the assignment does not contain an explicit cast. The missing cast may trigger an incorrect compiler warning (e.g. Clang).

Prevention of compiler warning

---

dlib/threads/async.h

As discussed in #1999, std::result_of is deprecated in C++17 and should be replaced by std::invoke_result. In C++20, std::result_of is removed. What I do in this PR is performing this replacement, when using C++17 or C++20. I used almost the same as in this other PR, from another library https://github.com/fmtlib/fmt/pull/1028.  
I also make a minor modification to how std::result_of is use for C++11 and C++14, to comply with how it is recommended (https://en.cppreference.com/w/cpp/types/result_of):  
```cpp
template<class F, class... Args>
std::result_of_t<F&&(Args&&...)> // instead of std::result_of_t<F(Args...)>, which is wrong
my_invoke(F&& f, Args&&... args) { 
/* implementation */
}
```
I ran all tests with gcc7, gcc9 and VS2017 (with C++14, and C++latest).

Replace result_of by invoke_result for C++17 and above #1999

---

dlib/http_client/http_client.cpp
dlib/linker/linker_kernel_1.cpp
dlib/md5/md5_kernel_1.cpp

With respect to issue #2017 I submit a few adjustments that mainly change the type of local variables to prevent potentially wrong integer conversions.

Integer conversions generating compiler warnings

---

dlib/dnn/loss.h
dlib/dnn/loss_abstract.h
dlib/test/dnn.cpp

This PR adds `loss_multiclass_log_weighted` for classification problems where we want to give more/less importance to some classes/samples.
I just took the idea from `loss_multiclass_log_per_pixel_weighted` by @reunanen and created this loss layer based on `loss_multiclass_log` for the sake of consistency.

add loss multiclass log weighted

---

dlib/cmake_utils/find_blas.cmake

openblasp is a parallel implementation of openblas with pthreads found on Centos/Fedora. See #2023

link against openblasp

---

dlib/dnn/trainer.h
dlib/dnn/trainer_abstract.h

Problem: As discussed starting from [here](https://github.com/davisking/dlib/issues/1381#issuecomment-598777029), the CUDA runtime allocates resources for each thread, and apparently those resources are not freed when the corresponding threads terminate. Therefore, each instantiation of `dnn_trainer` leaks a bit of GPU memory.
Solution: Add possibility to pass thread pools from outside. This way, subsequent `dnn_trainer` instances can use the same threads, and there's no memory leak.

To avoid a GPU memory leak, allow passing thread pools to dnn_trainer from outside

---

dlib/cuda/cuda_dlib.cu

As you commented in https://github.com/davisking/dlib/pull/2033#discussion_r395625551, having a branch like that might not be the best thing to do, so I've removed a similar branch from the gradient computation of the mish activation layer. I am not completely happy about having that lambda expression repeated, maybe as a function outside? But I didn't want to pollute the outer scope. What do you think?

remove branch from cuda kernel

---

dlib/dnn/layers.h
dlib/test/CMakeLists.txt
dlib/test/dnn.cpp
dlib/test/is_same_object.cpp
dlib/threads/async.h
examples/dnn_dcgan_train_ex.cpp
examples/dnn_instance_segmentation_train_ex.cpp
examples/dnn_introduction3_ex.cpp

As I've been running the tests several times these last days, I noticed there were some warnings when building with GCC 9.3.0 and these flags:
``` cmake
if (CMAKE_COMPILER_IS_GNUCXX)
add_definitions("-W -Wall")
add_definitions("-Wno-unused-function -fdiagnostics-color=always -Wno-deprecated-copy -Wextra -pedantic")
endif()
```
I might try the deprecated-copy warnings another time :)
Also, while I was at it, I made the `layers.h` a bit more uniform when there are unused parameters in methods like `serialize`.

Fix warnings while running the tests

---

examples/dnn_dcgan_train_ex.cpp

That comment was there from when I was using a dnn_trainer to train
the discriminator network.
Sorry for the noise, but that comment might confuse users...

Remove outdated comment from DCGAN example

---

dlib/dnn/trainer.h

The thread pool was initialized after the network, so it lead to a
reorder warning in GCC 9.3.0

Fix warning in dnn_trainer initialization list

---

dlib/image_processing/generic_image.h
dlib/image_transforms/interpolation.h
dlib/image_transforms/interpolation_abstract.h
dlib/pixel.h
dlib/test/image.cpp
dlib/test/serialize.cpp

Now `lab_pixel` and `rgb_alpha_pixel` will work with `interpolate_bilinear()`. Previously `lab_pixel` would become desaturated on interpolation.
Added `get_component<index>(pixel)` to ease up generic template programming.
Code is ready for any color space represented with cartesian coordinates and won't compile for polar ones (HSI), as it would require a bit more complicated blending.
Seems CIELAB is actually perfect for interpolation and theoretically should perform better for DNN than e.g. HSI where H component "wraps around":
http://davidjohnstone.net/pages/lch-lab-colour-gradient-picker
http://fse.studenttheses.ub.rug.nl/15441/1/CS_BA_2017_Jonathan_Hogervorst.pdf
https://en.wikipedia.org/wiki/CIELAB_color_space
https://en.wikipedia.org/wiki/HSL_and_HSV
`interpolate_quadratic` not …

Corrected interpolate_bilinear for lab_pixel.

---

dlib/dnn/core.h

I got this error few times and each time spent a lot of time guessing what I did wrong. In bigger networks it's easy to by mistake create `add_skip_layer<123, ...>` where there is no `add_tag_layer<123, ...>`. This produces gibberish error in header far from place of mistake.
Hopefully with this comment me and other people will easier get what's wrong.
The error one gets now in MVSC is:
`error C2039: 'subnet': is not a member of 'dlib::input<std::array<dlib::matrix<T,0,0,dlib::default_memory_manager,dlib::assignable_ptr_matrix<T>::layout_type>,3>>'`
... that for just network type definition:
`relu<skip1<tag2<input<::std::array<matrix<float>, 3>>>>> test;`

Additional documentation for failed dlib::layer<> use.

---

dlib/geometry/vector.h
dlib/matrix/matrix.h

Previously they were restored to default values, which had the effect of negating the current setting of the calling code (whether set in the compiler options or by pragma previously)

Fix restoration of MSVC warnings in public headers

---

dlib/dnn/loss.h
dlib/dnn/loss_abstract.h
dlib/test/dnn.cpp

Hi! I am planning on adding a multilabel loss layer to dlib.
The main motivation is, obviously, to be able to output multiple labels for a single image.
I know that `loss_multimulticlass` exists, but it is not quite the same, although one could achieve a similar result using as many classifiers as labels and two labels per class (present / not present);
I think the `loss_multilabel_log` I am suggesting might have some advantages:
- easier to use, since we don't need to fiddle with several `std::map<std::string, std::vector<std::string>>`
- it will allow for label smoothing in single label multiclass classifers
However, I have some questions with regards to the implementation.
- should the labels be `std::vector<float>` or `matrix<float>`: I think vectors are more intuitive, but matrices …

loss multibinary log

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h

I just noticed these two methods were missing for `mult_prev`.

Add missing input/output mappings to mult_prev

---

dlib/dnn/trainer.h

As discussed in #2163, this PR adds a check and a helpful message to inform the user that the tensor sizes in the devices have different size, probably due to an external modification of some network parameters after trainer construction

Add error message for mismatched tensor sizes in dnn_trainer

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/test/dnn.cpp

As discussed in #2157, this PR adds a new layer (`scale_prev_`) which is the same as `scale_` except that the inputs are swapped, which is useful since it allows mapping between inputs and outputs of this layer.

Add scale_prev layer

---

dlib/test/vectorstream.cpp
dlib/vectorstream/vectorstream.h

These updates ensure that casting ```dlib::vectorstream&``` to ```std::iostream&``` still works fine.

vectorstream updates: added seekoff and seekpos

---

dlib/vectorstream/vectorstream.h

After updating to latest dlib I got a warning about unused variable, so I changed the `DLIB_ASSERT` to `DLIB_CASSERT`. I am guessing we always want to check the `mode` we're in.

Use DLIB_CASSERT to avoid unused variable warning in release compilation

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/test/dnn.cpp

Hi, in this PR I implemented the [Gaussian Error Linear Unit (GELU)](https://arxiv.org/abs/1606.08415) activation layer.
This layer is often used in [Transformers](https://arxiv.org/abs/1706.03762).
The gelu function is defined as:
I choose the sigmoid approximation for this implementation. For the [derivative](https://www.wolframalpha.com/input/?i=derivative+of+x+*+sigmoid%28x+*+1.702%29), I used WolframAlpha... 😅
I would like dlib to support Transformer architectures some day, since they are proving to be really good at NLP tasks (they've made RNNs obsolete).
I will certainly give it a go in my spare time, but I can't promise anything or give a deadline. This is my first baby step (I know, I started building the house from the roof).
I think most of the building blocks are already …

Add GELU activation layer

---

dlib/dnn/trainer.h
dlib/test/statistics.cpp

This PR adresses issue #2206, which makes the `dnn_trainer` backtrack to a previous state when the loss sequence looks like:
```
1, inf, inf, inf, inf
```
https://github.com/davisking/dlib/blob/3ba004f875d02c4c326f8cec5d9ec46b5708ea5a/dlib/dnn/trainer.h#L1128-L1129
`probability_values_are_increasing` gives `nan` whenever an `inf` value is present, but not `probability_values_are_increasing_robust`. However, the latter will give `nan` if there are still `inf` values after discarding 10% of the samples.
Here we just check that `probability_values_are_increasing_robust` is not `nan` before saving to disk.
I've also added some checks to make sure we get the expected `nan` values, since the `dnn_trainer` relies on them.

fix backtracking when losses stay at inf (fixes #2206)

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/test/dnn.cpp
examples/dnn_dcgan_train_ex.cpp

This is a second step towards implementing transformers in dlib.
This PR adds [Layer Normalization](https://arxiv.org/abs/1607.06450) support to dlib.
I have added the CPU implementation and the forward GPU, but I have some doubts, so I would really appreciate if somebody could have a look to the CUDA implementation.
It runs slower than the CPU version and for big inputs (2, 3, 224, 224) results are not good, but for small inputs, it works.
Here's how I tried it, in case anyone wants to try
``` c++
#include <dlib/dnn.h>
using namespace dlib;
int main() try
{
auto print_tensor_and_avg = [](const tensor& t)
{
float sum = 0;
const float* p_t = t.host();
for (long n = 0; n < t.num_samples(); ++n)
{
// std::cout << "sample: " << n << '\n';
for (long k = 0; k < t.k(); ++k)
{
// std::cout << …
```

Add Layer Normalization

---

dlib/cuda/cuda_dlib.cu

I didn't notice this when I submitted the PR. `nvcc` complained about an unreferenced variable, so I removed it, as well as some old code from when I was implementing/debugging this layer.
Sorry about that :(

Remove an unused variable and old commented code in layer_norm

---

dlib/dnn/trainer.h

So, maybe this a bit controversial...
When I train networks, I like to fill all the fields of the `dnn_trainer` so that they all appear in my training log, and then access them from the trainer (`get_min_learning_rate()`, `get_mini_batch_size()`, etc...)
I found myself logging the minibatch-size manually many times, so finally I decided to make the `dnn_trainer` print it.
I was hesitating to submit this PR because, when you build your minibatches manually, and print the trainer to the screen, users might be surprised to see a `128` for the minibatch size (default value). But then I thought that it is already the case with the minimum learning rate, if you train with your own custom loop.
Anyway, feel free to reject it if you think it's not a good idea :)

Make dnn_trainer print the minibatch size to ostream

---

dlib/dnn/utilities.h

Minor fix, but when compiling with `-Wall -Wextra -pedantic`, I got a really huge nested warning when converting big networks to xml.
EDIT: I hope I am not bothering you with all these tiny PR...

Fix unused parameter warning in visitor_net_to_xml

---

tools/python/src/image2.cpp

I found I needed this for:
1. Visualizing the positions of the chips on video
2. Calibrating chip extraction based on different facial keypoint models

Expose get_face_chip_details to Python

---

tools/python/src/matrix.cpp

I've added serialization support for matrices (I know they are already pickable).
I was facing the following problem: I had to load some numpy arrays, but I wanted to work with them in C++. After looking online on how to load them, I realized that the easiest way was to make dlib do it for me:
``` python
import numpy as np
from dlib import matrix
arr = np.random.rand(10, 2)
matrix(arr).serialize("rand.dat")
m = matrix()
m.deserialize("rand.dat")
```
The good thing is that now I can deserialize the `rand.dat` from C++.
Maybe there's a better way of doing it, but I think having this is pretty convenient.

Add support for matrix serialization to python API

---

tools/python/src/simple_object_detector_py.h

A small modification to release the GIL in the face_detector. Since the face_detector seemed to be single-threaded, I made this change. 
I wrote some simple code to benchmark:
```python
files = sys.argv[1:] * 16
def basic():
detector = dlib.get_frontal_face_detector()
for f in files:
img = dlib.load_rgb_image(f)
dets = detector(img, 1)
def threads(num_threads=8):
file_chunks = np.array_split(np.asarray(files), num_threads)
def work(files):
detector = dlib.get_frontal_face_detector()
for f in files:
img = dlib.load_rgb_image(f)
dets = detector(img, 1)
threads = []
for i in range(num_threads):
threads.append(threading.Thread(target=work, args=(file_chunks[i],)))
threads[-1].start()
for thread in threads:
thread.join()
import os; print(os.cpu_count())
num = 1
print("basic", …
```

Release GIL before detecting faces

---

dlib/cuda/cuda_dlib.cu

Fixes:
- ::floor() -> ::floorf() which should be same as float is used, yet otherwise compiler complains host function can't be used from global.

Fixed CUDA 11.1 compilation.

---

dlib/simd/simd4f.h

Clang doesn't implement vec_rsqrt.
Code taken from https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/vsx_utils.hpp#L360

Fix build with clang on ppc64le

---

dlib/global_optimization/find_max_global.h

Previously, find_min_global would produce wrong output when passed
a collection of initial evaluations because the solver expected the y values to
be multiplied by -1.  This fix does that when minimizing.
closes #2283

fix find_min_global finding wrong answers

---

dlib/pixel.h

It's possible when #include-ing ```<dlib/matrix.h>``` in a header file to get the compiler error messages:
```
/usr/local/include/dlib/matrix/../pixel.h:1012:20: error: call to 'max' is ambiguous
/usr/local/include/dlib/matrix/../pixel.h:1013:32: error: call to 'min' is ambiguous
/usr/local/include/dlib/matrix/../pixel.h:1014:32: error: call to 'min' is ambiguous
/usr/local/include/dlib/matrix/../pixel.h:1083:29: error: call to 'min' is ambiguous
/usr/local/include/dlib/matrix/../pixel.h:1084:29: error: call to 'min' is ambiguous
...
```
This PR fixes this.

Compiler error bug fix when including <dlib/matrix.h> in a header file

---

dlib/dnn/trainer.h

Since we are dividing by 1024, the unit should be MiB instead of MB.
I also added a space between the number and the unit.

Minor fix in the network size format

---

dlib/matrix/matrix_utilities.h
dlib/matrix/matrix_utilities_abstract.h
dlib/test/matrix4.cpp

Just a small PR to add point wise pow for matrices, I found this useful to implement the [PDF of the Dirichlet distribution](https://en.wikipedia.org/wiki/Dirichlet_distribution#Probability_density_function).
I wondered whether I should call it just `pow`... since there are already [two overloads](http://dlib.net/dlib/matrix/matrix_math_functions_abstract.h.html#pow):
- `scalar, matrix`
- `matrix`, `scalar`
- `matrix`, `matrix`?

Add matrix pointwise_pow

---

dlib/image_transforms/interpolation.h
dlib/image_transforms/interpolation_abstract.h
dlib/test/image.cpp

Would you be interested in this kind of image transformation?
I have some doubts about this implementation:
- it's named `letterbox_image` but it also scales the image to fit a square of `size` × `size`
- I did this because it's the more common case and the user can always set it to `std::max(img_in.nr(), img_in.nc())`
- but maybe there should be an overload?
I have the (long term) goal of implementing YOLO training in dlib at some point in my life... This would come in handy, since YOLO trains with square images, and this would allow to convert the bounding boxes between the original and the letterboxed images.
I've already tried it locally initializing a `rectangle_transform` with the output of this function, and it's pretty convenient.

Add letterbox image

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h

I just noticed that in #2285 I didn't implement the `clipped_relu` layer as an in place layer, so this PR fixes that.
Also, the documentation for `clipped_relu` and `elu` was lying about their in place behavior, so I fixed that, as well.
Sorry for missing it in the first PR... :(

Make clipped-relu inplace and fix docs for elu

---

dlib/image_transforms/morphological_operations.h

Hi, I replaced a quote character in the comments of image_transforms/morphological_operations.h,
such that when compiling on Windows, it does not complain of file containing unicode character which is not in current codepage.
It is annoying because this warning pops up for every file compiled that includes this file.

replace a unicode character to suppress warnings

---

dlib/algs.h
dlib/type_safe_union/type_safe_union_kernel.h

This PR changes the stack-based memory block used by ```dlib::type_safe_union``` from ```stack_based_memory_block``` to ```std::aligned_union```
I can foresee Davis asking: "Why change something that ain't broke?" 
That would be a good point.
Because, since C++11, ```std::aligned_union``` has been around to do precisely this kind of thing. So why not use it and deprecate ```stack_based_memory_block``` ? As a rule of thumb, if there is something in the standard library that does precisely what you want to do, then use it.
As an aside, I think using ```reinterpret_cast``` instead of ```static_cast``` is more correct and guaranteed to work since proper alignment is satisfied.

[TYPE_SAFE_UNION] use std::aligned_union instead of stack_based_memory_block

---

dlib/CMakeLists.txt

As seen in #2353 and #2354, CentOS 7 ships with gcc 4.8.5, which is no longer supported in dlib since v19.22.
I think rejecting to build with that GCC version and pointing the users to an older version of dlib might be useful.

do not attempt to build with gcc 4.8.5 or older

---

dlib/dnn/layers.h

In [my implementation](https://github.com/dlib-users/dnn/blob/master/src/classification/repvgg.h) of the [RepVGG](https://arxiv.org/abs/2101.03697) network family, I was getting a compile error when running `disable_duplicative_biases`.
The case where a normalization layer has a skip layer as an input was not handled.

Fix disable_duplicative_biases when the input is a skip layer

---

dlib/image_transforms/interpolation.h
dlib/image_transforms/interpolation_abstract.h

This PR might introduce a breaking change.
Currently, `extract_image_4points` returns `void`, this PR changes it to return the `point_transform_projective` that maps points from the input image to the output image.
The main purpose of this is to be able to do "perspective" data augmentation on object detection, which need this transform to map the modified bounding boxes.

return the projective transform in extract_image_4points

---

dlib/dnn/trainer.h
dlib/statistics/running_gradient.h

I've been experimenting a crash when I change the learning rate scheduler in the trainer:
```
step#: 1967  learning rate: 0.000933682  average loss: 10.9136      percent complete: 98.35%
burn-in finished
**************************** FATAL ERROR DETECTED ****************************
Error detected at line 234.
Error detected in file ../../external/dlib/dlib/../dlib/dnn/../statistics/running_gradient.h.
Error detected in function double dlib::find_upper_quantile(const T&, double) [with T = std::deque<double>].
Failing expression was container.size() > 0.
******************************************************************************
```
Relevant part of the code:
``` c++
std::cout << "burn-in finished" << std::endl;
trainer.get_net(dlib::force_flush_to_disk::no); …
```

Fix running gradient crashing sometimes

---

dlib/image_transforms/draw.h
dlib/image_transforms/draw_abstract.h

In this PR, I added a function to compute the dimensions (in pixels) of the given string, using a particular font, similar to OpenCV's [getTextSize](https://docs.opencv.org/4.5.3/d6/d6e/group__imgproc__draw.html#ga3d2abfcb995fd2db908c8288199dba82).
It is mostly copy-paste of the `draw_string` function, but I couldn't see an easy way to reuse it.
I have some doubts:
- right now, I am returning a `std::pair<long, long>` so we can do `auto [w, h] = compute_string_dimensions("hello");`
- maybe `width` and `height` should be out parameters in the function, instead, or return a `matrix<long>`? I find structured bindings really convenient, though.
- I kept the `first` and `last` parameters, for coherence with the other methods, but I don't know if they are useful here.
- I am not sure about the …

Add function to compute string dimensions in pixels

---

dlib/console_progress_indicator.h
dlib/image_processing/shape_predictor_trainer.h

This PR adds progress information (current/total and percent) to console_progress_indicator.
Before it used to look like this:
```
Time remaining: 12 seconds.
```
But now it looks like this
```
Progress: 2172/5000 (43.44%). Time remaining: 12 seconds.
```
I've found myself adding this extra information many times in my code: most of the time, I want to know the actual number of elements completed out of the total, and the actual progress.
If you don't think this is useful, either close this PR, or tell me to add an extra `display_percent` parameter to the function.

Add progress information to console_progress_indicator

---

dlib/dnn/trainer.h

This PR makes the trainer print the number of parameters next to the network size if it has already been allocated (to avoid printing 0)

Show number of parameters if net is allocated

---

dlib/dnn/layers.h

`disable_duplicative_biases` prevents from building successfully if the input of the batch normalization layer is a tag layer, but there is no repeat layer afterwards. This PR fixes that.

Handle tag layers as inputs to disable_duplicative_biases

---

dlib/algs.h

After updating to CUDA 11.5, I got this warning:
```
dlib/algs.h(25): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead
```
According to this [blog post](https://developer.nvidia.com/blog/reducing-application-build-times-using-cuda-c-compilation-aids/), diagnostic pragmas without the `nv_` prefix have been deprecated, so I applied the proposed fix.

Fix nvidia pragma warning

---

dlib/invoke.h
dlib/test/invoke.cpp

See title.
This has required a refactor of `dlib::invoke` as `std::mem_fn` is not constexpr in C++11.

[INVOKE] added is_invocable_r, invoke_r, made everything constexpr and conditionally noexcept

---

examples/dnn_self_supervised_learning_ex.cpp

I am not sure this is needed, since the accuracy doesn't change, but I think it's good practice to normalize the samples for SVM classifiers. What I noticed, though, is that the best C is no longer around 3000, but around 30 (I modified the search range afterwards).
If you think it's unnecessary, reject this :)
EDIT: I am reusing the `vector_normalizer` learned from the training samples on the testing set, I don't think it's fair to learn a new normalizer.

Normalize samples for SVM classifier

---

dlib/matrix/matrix_read_from_istream.h

This pull request deals with issue #2459 
It allows to read CSV with semicolon separator to matrix. It is a very small change but it helps!

Add semicolon as separator for reading in a matrix

---

dlib/matrix/matrix_la.h

Resolves #2464, it seems. No idea why exactly, though.

Avoid distracting compiler warning

---

dlib/dnn/core.h
dlib/dnn/core_abstract.h

So, as I mentioned in #2292, it can be useful, sometimes, to inspect the intermediate gradients in the network.
Notable use cases include computing things like [GradCAM](https://arxiv.org/abs/1610.02391), or cumulating the gradients before back propagation to use a larger batch size.
With this PR, you can do something like:
```c++
net.compute_loss(x, labels.begin());
net.back_propagate_error(x, false);  // the false here means "don't zero out gradients automatically"
const auto& gi = net.subnet().get_gradient_input();  // before this PR this would always be zero.
// do something with the gradients...
net.zero_out_gradients();  // zero out input gradients for next iteration
```
I've updated the `back_propagate_error` and `compute_parameter_gradients` to have an extra boolean defaulted to …

add option to not zero out gradients and method to do it

---

dlib/geometry/rectangle.h

After #2481, several warnings appear when building with GCC. This PR fixes that.

Fix MSVC pragma warnings with other compilers

---

dlib/geometry/point_transforms.h

I was thinking that it makes more sense, if I pass a `drectangle` to the `rectangle_transform`, to get a `drectangle` whose coordinates have not been rounded. What do you think?
I noticed this with YOLO detectors, since I use `letterbox_image`, I need to transform the detections back to the original image space. I was surprised to see that all detections had integer coordinates for their bounding boxes.

Do not round drectangle in rectangle transform

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/core.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/external/pybind11/include/pybind11/numpy.h
dlib/test/dnn.cpp
docs/docs/ml.xml
docs/docs/term_index.xml

This PR adds a simple Reorg layer.
I think it was introduced in YOLOv2 (and YOLOR uses it as well) instead of a strided convolution for down-sampling in the first layer.

Add Reorg Layer

---

dlib/test/mpc.cpp

I jast saw that the MPC test fails on macOS, so I relaxed the condition a bit.
https://github.com/arrufat/dlib/runs/5046699340?check_suite_focus=true

Relax MPC test for macOS

---

.github/workflows/build_cmake.yml

Thought it might be nice to have Github Actions build the examples, too? Just to catch as many issues as soon as possible?
Apparently there's some issue with the Windows builds (think @arrufat ran into that as well?), but I don't think this needs to prevent us from doing it on the other OSes/compilers?

Make Github Actions build more stuff (in particular, the examples)

---

dlib/test/statistics.cpp

`std::random_shuffle` has been deprecated since C++14.

Do not use deprecated `std::random_shuffle`

---

dlib/rand/rand_kernel_1.h
dlib/rand/rand_kernel_abstract.h
dlib/test/mpc.cpp
dlib/test/rand.cpp

I was trying to implement the [mixup paper](https://arxiv.org/abs/1710.09412) and I noticed they use the beta distribution to generate the blending parameter α.
So, I tried to implement it myself and added to the `dlib::rand`.
I got **a lot** of “inspiration” from the [NumPy code](https://github.com/numpy/numpy/blob/1995e2cdfd17ec75e37cc6e69a42ce9000aac966/numpy/random/src/distributions/distributions.c#L406-L439).
@pfeatherstone, since you added already 2 distribution generators (Weibull and Exponential) would you mind having a look?
Specially, I am a bit puzzled about line 421 in the NumPy code. It looks like that condition will be always true inside that block. Am I missing something? If I implement it the same way as them, the code gets stuck in an infinite loop :(

Add get_random_beta to dlib::rand

---

.github/workflows/build_cmake.yml

Here's an alternative solution to #2508, but this one includes also two Clang jobs on `ubuntu-latest`: one on the current default Clang 11, but also another job explicitly on version 13.
I guess it's a matter of taste if you prefer a matrix, or just a list of jobs. A matrix is nice if you don't have too many exceptions that you need to cover by adding `if` conditions. This one gets a bit verbose, maybe – although I do believe that some deduplication could be done. (Had just a quick look at the options, but didn't find anything that would have looked particularly appealing...)

Make GitHub actions build on gcc-11 and clang too

---

dlib/dnn/loss.h
examples/dnn_self_supervised_learning_ex.cpp

It's a really minor fix (basically a typo), which I only noticed now.
A factor of 2 in the derivative of the Barlow Twins loss is missing. It's no big deal, since it can be compensated by setting a larger lambda, but still. It's even mentioned in the comment above…
I am running the example again, but I think nothing will change.

Fix Barlow Twins loss gradient

---

dlib/cuda/cudnn_dlibapi.cpp

**Problem**: `Error while calling cudnnGetConvolutionBackwardFilterWorkspaceSize( context(), descriptor(data), descriptor(dest_desc), (const cudnnConvolutionDescriptor_t)conv_handle, (const cudnnFilterDescriptor_t)filter_handle, (cudnnConvolutionBwdFilterAlgo_t)backward_filters_algo, &backward_filters_workspace_size_in_bytes) in file C:\a\1\s\3rdparty\dlib\dlib\cuda\cudnn_dlibapi.cpp:1048. code: 9, reason: CUDNN_STATUS_NOT_SUPPORTED`
**Solution**: Do not apply the cuDNN 5.1 workaround if we have cuDNN version greater than or equal to 7
---
Apparently `cudnnFindConvolutionBackwardFilterAlgorithm` isn't deterministic (which is understandable), so the issue may not be easy to reproduce.

Fix error calling `cudnnGetConvolutionBackwardFilterWorkspaceSize`

---

dlib/cuda/cudnn_dlibapi.cpp
dlib/cuda/cudnn_dlibapi.h

Problem: `Error while calling cudnnGetConvolutionForwardWorkspaceSize( context(), descriptor(data), (const cudnnFilterDescriptor_t)filter_handle, (const cudnnConvolutionDescriptor_t)conv_handle, descriptor(dest_desc), (cudnnConvolutionFwdAlgo_t)forward_algo, &forward_workspace_size_in_bytes) in file C:\a\2\s\3rdparty\dlib\dlib\cuda\cudnn_dlibapi.cpp:1029. code: 9, reason: CUDNN_STATUS_NOT_SUPPORTED`
Solution: when this happens, select the best algorithms again - but this time bypassing the cache
This PR addresses the same problem as does #2531, but in a different way.

Fix error calling `cudnnGetConvolutionForwardWorkspaceSize` – alternative approach

---

dlib/dnn.h
dlib/dnn/visitors.h
dlib/dnn/visitors_abstract.h

As mentioned in #2521, I've made a visitor to draw a neural network diagram in the [DOT](https://www.graphviz.org/doc/info/lang.html) language.
There's certainly room for improvement, as it requires specializing the methods for each layer manually.
However, its usage is really straightforward (exactly the same as the `net_to_xml` visitor) and it can draw arbitrarily complicated networks.
Here's an example with the [`resnet.h`](../tree/master/examples/resnet.h) file from the examples:
> `net_to_dot.cpp`
```c++
#include <dlib/dnn.h>
#include "resnet.h"
int main()
{
resnet::train_18 net;
net_to_dot(net, std::cout);
// we can also make it write the output to a file directly, to inspect it and modify it
net_to_dot(net, "net.gv")
}
```
Then, we just run it like this:
```bash
./net_to_dot | dot …
```

Add visitor to draw nets in the DOT language

---

dlib/dnn/loss.h
dlib/dnn/loss_abstract.h
docs/docs/release_notes.xml

As suggested in #2545, this PR modifies the existing `loss_multibinary_log_`, introduced in #2141 to support the gamma parameter presented in the Focal loss.

Add focal gamma to loss_multibinary_log

---

dlib/dnn/loss.h

I could have fixed it just by replacing the `||` by `&&`, but I wanted to set the `gamma` explicitly as well, like you do in the `loss_metric_`

Fix deserialize logic in loss_multibinary_log

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/dnn/visitors.h
dlib/test/dnn.cpp
docs/docs/ml.xml
docs/docs/release_notes.xml
docs/docs/term_index.xml

For a while, I've been looking for an activation to replace ReLU.
I want a smoothed version that can be computed fast and in-place. SiLU, Mish, GELU don't fit the bill in some of those points.
Today, I found about [SmeLU](https://ai.googleblog.com/2022/04/reproducibility-in-deep-learning-and.html) ([paper](https://arxiv.org/abs/2010.09931)) (it has a really weird name). And I've implemented it as an in-place operation, so it will use the same amount of memory as a ReLU layer when training and inferring.
I've also updated some tests to actually check for negative values, i.e., replacing `rnd.fill_uniform` with `rnd.fill_gaussian`.

Add SmeLU activation

---

.github/workflows/build_cpp.yml
dlib/test/serialize.cpp

I was trying to wrap my head around #2506, mostly because I would like to enable GitHub Actions for gcc 11 as well.
However, at least so far I couldn't find a solution where we could (de)serialize `std::vector`s of `my_custom_type`, if `immutable_type` is an alternative in the `q` variant. At least cleanly and without defining a custom move assignment operator for `my_custom_type`, or doing other (presumably) unwanted things. Not even sure if pushing such variants to a vector should be possible to begin with, as per the C++ standard – maybe gcc 11 is just doing the right thing here?
So here is one workaround, where we simply don't put such variants in vectors. We can still (de)serialize _standalone_ variants that can hold an immutable alternative.
@davisking, @pfeatherstone, @arrufat – …

Workaround for #2506

---

tools/imglab/src/cluster.cpp
tools/imglab/src/common.cpp
tools/imglab/src/common.h
tools/imglab/src/flip_dataset.cpp
tools/imglab/src/main.cpp

It should have been included in #2565.
I just noticed imglab couldn't find a dataset with WebP images.

Add WebP support to imglab

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/dnn/visitors.h
dlib/test/dnn.cpp

Simple PR to add support for the Sigmoid Linear Unit (SiLU) activation layer.
This layer is quite popular in recent state-of-the-art models such as YOLOv5 and EfficientNetV2.
It is, however, a relatively “old” activation layer, introduced in 2016 in the [GELU paper](https://arxiv.org/abs/1606.08415).
So, I thought it would be a nice addition to dlib :)

Add SiLU activation layer

---

dlib/image_saver/save_webp.h
docs/docs/release_notes.xml

I just noticed that there was a problem when saving grayscale images in WebP format.
WebP does not support single-channel images, so we need to save them as RGB, which we were doing.
However, the stride was wrong: I was using the stride as if it were a single-channel image, so we need to recompute it before saving.
This PR addresses this issue.
Fun fact: even though we save a lossless RGB image in WebP, it still takes less disk space than the grayscale PNG, at least for the images I tried.

Fix saving grayscale WebP images

---

dlib/image_saver/save_webp.cpp

I just noticed that, if we successfully encode an image into WebP, but fail to write it to disk for some reason, we must free the encoded image in memory. Otherwise, we would leak memory.

Fix memory leak when writing WebP throws

---

dlib/console_progress_indicator.h
dlib/threads/parallel_for_extension.h
docs/docs/release_notes.xml

Hi, I've updated a little bit the `console_progress_indicator`.
Since C++11 is a minimal requirement for dlib, it now uses `std::chrono` for all time manipulations (I really like `std::chrono`).
I've also added a `finish` method that will print the completed progress and the ellapsed time.
While running (subsequent calls to `print_status`):
```
Progress: 51/1000 (5.10%). Time remaining: 1min 34s.
```
After calling `finish`:
```
Progress: 1000/1000 (100.00%). Time elapsed: 1min 39s.
```
This `finish` method is meant to be called after a loop so that you don't need to remember the estimated time the first call to `print_progress` printed.
I hope you like it :)

Use chrono in console progress indicator and add finish method

---

examples/dnn_self_supervised_learning_ex.cpp

A small typo fix to trigger the CI.

Fix typo in the self-supervised learning example

---

dlib/dnn/loss.h
dlib/dnn/loss_abstract.h

Here there are some (backwards-compatible) for the YOLO layer:
- use the Smoothed L1 norm in the bounding box regression to stabilize the training.
- optional focal losses for the objectness and classifier.
- use the `truth.detection_confidence` as the positive weight for the classification loss.  This could be used to handle imbalance in the classifier.
By doing so, on an internal dataset, I was able to gain 1 mAP point.
I also added [Adaptive Training Sample Selection (ATSS)](https://arxiv.org/abs/1912.02424): when `iou_anchor_threshold` is set to 0, the threshold will be adjusted adaptively for each ground truth, according to how it matches the anchors. The motivation is:
- if an anchor matches really well (high IoU), the threshold will be high and other anchors won't be used. 
- if no …

YOLO improvements: Smoothed L1 loss, Focal Loss, Weighted Loss

---

dlib/bigint/bigint_kernel_2.cpp
dlib/geometry/drectangle.h
dlib/geometry/rectangle.h
dlib/gui_widgets/canvas_drawing.h
dlib/image_keypoint/hessian_pyramid.h
dlib/image_keypoint/surf.h
dlib/image_transforms/draw.h
dlib/image_transforms/fhog.h
dlib/image_transforms/image_pyramid.h
dlib/image_transforms/interpolation.h
dlib/matrix/matrix_math_functions.h
dlib/test/CMakeLists.txt
dlib/test/fhog.cpp
examples/dnn_self_supervised_learning_ex.cpp

I have some time to kill, and I want to modernize some rounding statements in dlib.
I think it won't break anything (I recently learned about `std::lround` and wanted to use it in dlib)

Modernize rounding and cast statements

---

dlib/cuda/cudnn_dlibapi.cpp

I was experienced an issue compiling Dlib with GPU and seeing the below error.
`-- Building a cuDNN test project to check if you have the right version of cuDNN installed...
-- *****************************************************************************************************
-- *** Found cuDNN, but we failed to compile the dlib/cmake_utils/test_for_cudnn project.
-- *** You either have an unsupported version of cuDNN or something is wrong with your cudDNN install.
-- *** Since a functional cuDNN is not found DLIB WILL NOT USE CUDA.
-- *** The output of the failed test_for_cudnn build is:`
`***   /home/dlib/dlib/cuda/cudnn_dlibapi.cpp:803:74: error: ‘allow_cache_use’ is not a class, namespace, or enumeration
***                if (iter != config_to_algo_cache.end() && allow_cache_use == …

Fix cuDNN test project bug

---

examples/dnn_self_supervised_learning_ex.cpp

This change makes the self-supervised example more close to reality:
usually, only a fraction of the dataset is labeled, but we can harness
the whole dataset by using a self-supervised method and then train the
classifier using the fraction of labeled data.
Using 10% of the labels results in a test accuracy of 87%, compared to
the 89% we got when training the multiclass SVM with all labels.
I just added an option to change the fraction of labeled data, so that
users can experiment with it.

Use only a fraction of labels for the multiclass SVM in SSL example

---

dlib/svm/auto.cpp
dlib/svm/auto.h
dlib/svm/auto_abstract.h
dlib/svm/svm_multiclass_linear_trainer.h
docs/docs/release_notes.xml
examples/dnn_self_supervised_learning_ex.cpp

As suggested in https://github.com/davisking/dlib/pull/2460#issuecomment-971569505, this PR adds the common following common use case for training multiclass SVM classifiers:
- normalize
- run cross validation to find the best setting
- train the final linear model
I am sure there is room for improvement, for instance, the type of the training samples `x`, which I set it to `matrix<float>` because that's what the neural networks return...
Maybe I could be generic in the type, or add an overload that converts `matrix<float>` to `matrix<double>` and just have that implementation?
As a side note, is there any reason why you prefer `typedef` over `using` syntax? I kind of like `using` more :P

Add multiclass SVM trainer to svm/auto.h

---

dlib/dnn/loss.h

Small improvements:
- Compute the input area and the truth area only once.
- Improve logic legibility for the `iou_anchor_threshold`.
- Make sure the input_area is a `drectangle` to avoid unwanted rounding operations:
- in particular when checking `input_area.contains(center(truth_box.rect))`
- the `.contains` method expects a `point` instead of a `dpoint` if `input_area` is a `rectangle`.
- I don't think it has much effect, but still.

Small YOLO loss improvements

---

dlib/image_transforms/random_color_transform.h

Just a small PR to modernize `random_color_transform` a bit:
- use `initializer_list` for `std::max`: I really like this.
- use `const` where possible
- use `static_cast` instead of C-style cast
I have run a small benchmark, but I couldn't find any speed difference, both implementations take about 0.0128127±0.00387623 ms to create a `random_color_transform`.

Modernize random_color_transform

---

dlib/CMakeLists.txt

fixes #2643 
@ShellMount Will this fix it? At least in my environment the problem is fixed.

Fixes Undefined symbols for architecture arm64

---

dlib/algs.h
dlib/any/any.h
dlib/any/any_decision_function.h
dlib/any/any_function_impl.h
dlib/any/any_trainer.h
dlib/bound_function_pointer/bound_function_pointer_kernel_1.h
dlib/bridge/bridge.h
dlib/constexpr_if.h
dlib/dnn/core.h
dlib/global_optimization/find_max_global.h
dlib/metaprogramming.h
dlib/overloaded.h
dlib/serialize.h
dlib/threads/thread_pool_extension.h
dlib/type_safe_union/type_safe_union_kernel.h
dlib/type_safe_union/type_safe_union_kernel_abstract.h
dlib/type_traits.h
dlib/utility.h
tools/python/src/global_optimization.cpp

I'm currently working on a dnn2 API. As I'm working on it, I'm spotting things in the code base that could do with a refresh.
This PR proposes some of these updates:
- old type traits are now just aliases for standard library type traits
- using `is_detected` and `switch_()` in dnn core. I think it makes things clearer and trivially update-able to `if constexpr` for when the time comes.
- added an improved `for_each_in_tuple()`. It uses fold expression if possible otherwise the parameter pack expansion trick into dummy initializer list. This improves compile time. 
- Use generic lambdas where possible instead of struct helpers
- auto deduced return types

Miscellaneous cleanup and refresh

---

examples/dnn_self_supervised_learning_ex.cpp

I was using the normalized features za as both matrices, instead of za and zb. I noticed this because the empirical cross-correlation matrix was symmetrical, which is not supposed to.  It does not affect anything, as it was computed properly in the loss.

Fix empirical cross-correlation computation in the SSL example

---

dlib/matrix/matrix_data_layout.h
dlib/test/CMakeLists.txt

Github actions is using a new version of GCC that has a bug in it.  As can be seen in the test results on #2690.  This change should fix it.

Suppress incorrect warning from gcc

---

dlib/matrix/lapack/fortran_id.h

This fixes a segfault in the newton search on ppc & mips 64 bits:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000550000679c in dlib::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > (this=0x550181aa50, A=...) at /usr/aarch64-linux-gnu/include/dlib/matrix/matrix_lu.h:130
130             if (piv(piv_temp(i)-1) != piv(i))
#0  0x000000550000679c in dlib::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > …
```

Fix newton segfault on ppc64/mips64

---

.github/workflows/build_cpp.yml
.github/workflows/build_python.yml

I found this on Reddit: https://www.reddit.com/r/cpp/comments/z618kl/psa_cmake_325_might_break_your_github_actions/
_The Meson devs, in their infinite wisdom, decided that it was a good idea to ignore 30 years old platform conventions and produce static libraries with a filename that implies GNU ABI on Windows, even when targeting MSVC ABI._
_CMake, in an attempt to accomodate, added this name pattern to its normal MSVC ABI search patterns in 3.25: https://gitlab.kitware.com/cmake/cmake/-/issues/23975
Since GitHub Actions runners are very frequently updating tools, this update quickly made it into the virtual envs._

Fix GitHub actions on Windows because of CMake 3.25.0

---

dlib/dnn/input.h
dlib/dnn/layers.h
dlib/dnn/loss.h

There were errors in some XML strings returned by to_xml in dnn/layers.h (fc, layer_norm). I also added newlines to various XML strings.
I noticed XML strings that may have errors in dnn/layers.h at lines 3181 (leaky_relu) and 3699 (smelu), i don't know if those should be changed as well

removed extra '<' in fc, added '\n' in layers/inputs/losses XML strings

---

dlib/test/CMakeLists.txt
examples/CMakeLists.txt

I think this is a good idea.
I always compile libav* libraries as static libraries.
I noticed that `dtest` was then 100MB in size.
Stripping in release mode reduces that to 20MB on my machine. That's pretty typical given a fully enabled installation of ffmpeg.
I don't want users to get scared and think that all their computer vision applications will be > 100MB in size. That's pretty crazy and easily avoidable by adding in `-s` to your link options.

Strip binaries in release mode

---

dlib/image_processing/box_overlap_testing.h

As explained in [this article](https://medium.com/analytics-vidhya/iou-intersection-over-union-705a39e7acef) the union for calculating the IoU of two rectangles must be the unified area of both rectangles. Currently the outer rectangle in that both rectangles fit is used, which is wrong, as this area is larger than the one that has to be used.

fix wrong union calculation in box_overlap_testing.h

---

dlib/simd/simd4f.h
dlib/simd/simd4i.h
dlib/simd/simd_check.h

The gcc altivec extension defines keywords for vector, bool, and pixel, both with underscores and without. However, unless another extension is used the keywords without underscores conflict with standard types.
To resolve the conflict use the keywords with underscores for the altivec vector types.
Fixes: #2711
Note: with this dlib can be compiled but crashes during tests. This crash is not specific to powerpc. There is probably something missing when neither the AMD nor the Arm vector implementation is available.

powerpc/altivec: use __vector instead of vector

---

.github/ISSUE_TEMPLATE/bug.yml

I guess a lot of people are building dlib to use it from Python, so add a field to allow them to report which version they're using.

Add optional Python version

---

dlib/gui_core/gui_core_kernel_2.cpp

This fixes a crash I was running into trying the dnn_face_recognition_ex with XQuartz on a Apple Silicon Mac.
It seems that the prebuilt libX11.6.dylib bottle from Homebrew is missing full locale support, which causes the XwcTextListToTextProperty call to return -2 (XLocaleNotSupported), which caused this code to crash when calling XFree as the XTextProperty value was not initialised.
Window titles seemed generally low value here, so just avoiding the crash seemed like the easiest path forwards.

Fix crash when libX11 is missing locale support

---

dlib/matrix/matrix_utilities.h
dlib/pixel.h
dlib/test/pixel.cpp

I needed to use HSV instead of HSI in dlib, so I added support for it.
Code adapted from [here](https://stackoverflow.com/questions/3018313/algorithm-to-convert-rgb-to-hsv-and-hsv-to-rgb-in-range-0-255-for-both).
I've compared it to the one provided by OpenCV and the results are identical.

Add HSV support

---

tools/imglab/src/flip_dataset.cpp

I tried to use the `--flip` and `--flip-basic` options in imglab, but it was complaining that the XML dataset did not exist. It turns out it was changing the current directory too soon.

Fix imglab changing the current dir too soon

---

dlib/geometry/polygon.h
dlib/image_transforms/draw.h
dlib/image_transforms/draw_abstract.h

This is my first attempt at filling an arbitrary polygon, not just a convex one, using the scanline algorithm. With my current implementation, it doesn't seem obvious to add antialiasing for the edges, though.
However, I use this for drawing a polygon in a mask image, and then blur the mask to alpha blend whatever I want using the polygon, so I get the nice antialiasing just by blurring the mask.
Simultaneously, I fixed some other stuff:
- since I copied the `draw_solid_convex_polygon` from the widgets, where the antialiasing was not optional, when it was disabled, we were painting an extra pixel on the borders.
- there were parts that assumed a `dlib::matrix` (my fault), so I fixed that too.
- I renamed `fill_convex_polygon` to `draw_solid_convex_polygon` (to match all the other …

Add draw solid polygon

---

dlib/sliding_buffer/circular_buffer.h

I don't know why, maybe because of branch prediction, or maybe because the `%` operator is very slow, but this is almost a 10X speedup improvement.

circular_buffer : 10X speedup

---

dlib/image_transforms/interpolation.h
dlib/image_transforms/interpolation_abstract.h
tools/python/src/image2.cpp

I think this function would be very convenient in the Python bindings to be able to revert the `extract_image_chip` without exposing the `transform` types in Python.
Exposing the `transform` tooling could be done at a latter time if there's a need for that, but I guess this function should cover most of the basic cases, such as #2595.

Add insert_image_chip

---

dlib/image_transforms/interpolation.h

I've updated the rest of the interpolation file to use `dpoint`.
Maybe that alias was introduced after all these functions?

Use dpoint instead of dlib::vector<double, 2>

---

dlib/constexpr_if.h
dlib/test/invoke.cpp
dlib/type_traits.h

`callable_traits` works on non-callable types, in which case it simply provides `callable_traits::is_callable == false`

[Meta] fixed callable_traits

---

dlib/media/ffmpeg_muxer.h
dlib/test/ffmpeg.cpp

Adds `encoder::push(const image_type&, Callback&&)` and `muxer::push(const image_type& )` where `image_type` is a dlib image type like `array2d<rgb_pixel>` or `matrix<bgr_pixel>`.

[FFmpeg] added push(image_type) methods to encoder and muxer

---

dlib/media/ffmpeg_demuxer.h
dlib/media/ffmpeg_details.h
dlib/media/ffmpeg_muxer.h
dlib/test/ffmpeg.cpp
examples/ffmpeg_file_to_speaker_ex.cpp

- Added `save_frame()`
- Added more code inside `muxer` for picking appropriate codecs when either not specified or not suitable.

[FFmpeg] added save_frame() and improved picking of codecs when not specified

---

dlib/image_transforms/interpolation.h

When using `interpolate_quadratic` some really bright/dark areas would present artifacts.
This PR fixes that by clamping the pixel values to their appropriate range before converting them.
(image resized from 512x512 to 5800+ using `interpolate_quadratic` and a pyramid, and then resized down to 512 using `interpolate_nearest_neighbor` for display purposes here)

Fix pixel saturation in interpolate_quadratic

---

.gitignore
README.md
dlib/image_transforms/interpolation.h
pyproject.toml
setup.py

Fixes #2803  by creating a minimal pyproject.toml that still uses the existing setup.py details to remove the deprecation warning. Updates the way Python package is compiled and adds the requirement `build`. I am not an expert but it seems to work!
Old method gave the following warnings:
```
/home/rover/Documents/tmp/dlib/venv-old/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
/home/rover/Documents/tmp/dlib/venv-old/lib/python3.11/site-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
```
New methods removes these …

Add minimal pyproject.toml

---

dlib/CMakeLists.txt

Some cblas symbols are called from public matrix headers:
```
2023-06-28T15:54:13.7379840Z Undefined symbols for architecture x86_64:
2023-06-28T15:54:13.7380810Z   "_cblas_daxpy", referenced from:
2023-06-28T15:54:13.7382310Z       dlib::blas_bindings::matrix_assign_blas_helper<dlib::matrix<double, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>, void>::assign(dlib::matrix<double, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> const&, double, bool, bool) in Dlib.cxx.o
2023-06-28T15:54:13.7387160Z       void …
```

Make cblas libs public

---

dlib/optional.h
dlib/test/CMakeLists.txt
dlib/test/optional.cpp
dlib/utility.h

This is work in progress.
This is inspired by Sy Brand's tl::optional repo and https://github.com/bitwizeshift/BackportCpp.git
I've tried a few different ways of doing things. For example, i didn't like using `union` but it turns out you can't use `aligned_storage` if you want things to be constexpr and direct initialization to work.
I have to say, this is an education in C++ initialization. It's laughable how complicated an object that is either active or None can be. C++ is so messed up. And yet, I love it

dlib::optional

---

.github/ISSUE_TEMPLATE/bug.yml

When I created the issue template, I was expecting that we would get fewer people opening bugs when they can't build dlib, so I added the bug label to all submitted bugs.
However, that is not the case, and we still get bug reports which are not really bugs, and this label prevents the @dlib-issue-bot from closing them if there's no activity.
I think the bug label should only be added manually after verifying that the bug report is actually a bug.

Remove bug label from the issue template

---

dlib/cuda/cudnn_dlibapi.cpp
dlib/dnn/layers.h

In PR #2656 we talked about separate convolution forward pass and bias addition, because for some reason, it was slower.
I was reading cuDNN documentation (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnActivationMode_t), and it says that function `cudnnConvolutionBiasActivationForward` with `CUDNN_ACTIVATION_IDENTITY` (as used in dlib at the moment), should only be called with algorithm `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM`. Maybe that's why it was running slower.
In this PR I combined both operations again, but only when forward algorithm is `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM`. I tested it with https://github.com/dlibml/dnn, using alexnet and darknet, and these were the results:
alexnet avg 23451 us -> 23267.5 us (the same)
darknet19 avg 24320 …

Perform convolution with bias addition combined for a specific algorithm 

---

dlib/cmake_utils/test_for_cudnn/find_cudnn.txt

I faced an issue as neither CUDNN_INCLUDE_DIR nor CUDNN_HOME environment variables were set. This resulted in a "Found cuDNN" error. Therefore, I updated the path with /cuda, as it was most suggested installation path for installing cudnn.

updated cudnn path

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cudnn_dlibapi.cpp
dlib/cuda/cudnn_dlibapi.h
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/dnn/visitors.h
dlib/dnn/visitors_abstract.h

This PR extends the fuse_layers method to also fuse convolutional layers followed by relu, and convolutional layers follower by affine followed by relu.
I tested it with `examples/dnn_mmod_face_detection_ex.cpp` and got exactly the same results on the images shown.
Here are also some tests for different neural networks from https://github.com/dlibml/dnn:
| Name         | master (w/o fusion) | master (w/ fusion) | this PR (w/o fusion) | this PR (w/ fusion) | comparative1 | comparative2 |
| :------------: | :-------------------: | :------------------: | :--------------------: | :-------------------: | :-------------: | :-------------: |
| alexnet      | 9.53                | 9.63               | 9.55                 | 9.45                | 1.84%         | 1.10%         |
| sqznet1.0    | …

Add fuse layers for conv+affine+relu and conv+relu

---

dlib/media/ffmpeg_demuxer.h

This is an urgent bug fix. Also, I can smell a dlib release coming. This needs to go in before that happens.

[FFMPEG] bug fix in demuxer when more than 2 streams are present

---

dlib/gui_core/gui_core_kernel_2.cpp
dlib/gui_widgets/nativefont.h
dlib/http_client/http_client.cpp

Apple Clang complains about sprintf and suggests using snprintf due to CVE bugs.

Use snprintf instead of sprintf

---

dlib/image_loader/png_loader.cpp
dlib/image_loader/png_loader.h
dlib/image_loader/png_loader_abstract.h
dlib/image_saver/save_png.cpp
dlib/image_saver/save_png.h
dlib/image_saver/save_png_abstract.h
dlib/test/image.cpp

* `save_png()` works with `std::vector<byte,alloc>`
* `save_png()` works with `std::ostream`
* Optimization for `bgr_pixel`. No longer have to convert image to `array2d<rgb_pixel>`
* Added tests to `image.cpp` which checks `save_png()` works with  `matrix`
* Added tests to `image.cpp` which checks the different ways of saving
* ~~I've temporarily removed the overload for `matrix` which converts to `array2d`. The tests don't fail so I don't know why it's there. It unnecessarily incurs a huge allocation. I imagine it handles the case where `matrix_exp` is an expression not a `matrix`. Who does that? Can we have an overload for that specifically?~~ I've added an overload for `matrix` and for `matrix_exp`. The latter does a copy. The former converts to `const_image_view` which is zero-copy.
* …

[PNG] save_png() now works with std::vector and std::ostream

---

pyproject.toml

It should be used system cmake instead of compiling own package. Compiling cmake is problematic because it takes a long time and needs a lot of additional packages that many systems doesn't provide.

Remove cmake from pyproject.toml

---

setup.py

`CMAKE_BUILD_PARALLEL_LEVEL` is a variable that can limit resources used during build: https://cmake.org/cmake/help/latest/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html
Unfortunately, when `-j` flag is set the variable is ignored. The patch allows to use of `CMAKE_BUILD_PARALLEL_LEVEL` and passes the value to `-j` flag.

Make use of CMAKE_BUILD_PARALLEL_LEVEL

---

dlib/geometry/vector.h
dlib/geometry/vector_abstract.h
dlib/test/geometry.cpp

So, I know I've not been very active on dlib really...
The thing is, at my current job I am using Zig quite a bit, and therefore, not using dlib as much as I'd like.
However, today I had to compute the convex hull of a set of points at work and checked if an implementation on dlib existed to port it to Zig, but I couldn't find it.
So I coded it in Zig, and now I am back porting it to dlib, as I think it may be useful.
Let me know if you think the stuff in the `impl` namespace should also be exposed to the users.

Add find_convex_hull using Graham scan

---

dlib/dnn/loss.h
dlib/dnn/loss_abstract.h
examples/dnn_self_supervised_learning_ex.cpp

This allows us to greatly simplify the self supervised learning example:
- the computation in user code was a bit too distracting
- avoids duplicated computation/allocation of this matrix
- avoids edge case where net outputs are zero due to trainer synchronization

loss_barlow_twins: add get_eccm member function

---

dlib/image_transforms/random_color_transform.h

No need to do anything if both gamma and color magnitudes are set to 0.

Return shortcut in disturb_colors

---

dlib/image_transforms/random_color_transform.h
dlib/image_transforms/random_color_transform_abstract.h

I've had the need to revert the output of dlib's `random_color_transform`.
As a result, I've refactored the code so that we now have
- `color_transform` object, which deterministically returns a transform for some given parameters
- `inv_color_transform` object, which returns the inverse color transform of the given color transform
- `random_color_transform` is now a function that returns the `color_transform` object generated with random parameters.
I understand this might break people's code for seemingly no reason, so, if you would rather not merge this, I'll figure a way around it :)
Let's see if all tests pass, first.

Add color transform and inv color transform

---

dlib/test/main.cpp
dlib/test/tester.cpp
dlib/test/tester.h

I stumbled across this while doing the CMake stuff.
I don't see any good reason why it's using dlib's own map container when there is a perfectly good one in STL. Also, use std::mutex and std::atomic instead of dlib pthread wrappers.

Use STD in testing suite

---

dlib/image_loader/load_image.h
dlib/image_saver/save_jxl.cpp

For some reason, JPEG XL can have two magic numbers. Adding the one that was missing here.

Add missing magic number for JPEG XL

---

dlib/threads/threads_kernel_1.h

Fix `std::unique_lock` usage in the Windows implementation of `dlib::signaler`

---

dlib/CMakeLists.txt

lapack/cblas libs are needed through the dlib/matrix/lapack headers
it can be verified on the optimization example:
https://github.com/jschueller/dlib-cmake-example

CMake: Set LAPACK libs as public

---

dlib/global_optimization/find_max_global.h
dlib/global_optimization/find_max_global_abstract.h

Prevents wrap observed in emcc, causing find_max_global to exit immediately unless a custom (and non-wrapping) max_runtime is provided.

Reduce FOREVER from 290 to 200 years

---

dlib/image_loader/load_image.h

This PR addresses an issue in the handling of API differences between various versions of the libgif library. Previously, the version check only accounted for the major version number, specifically checking if the GIFLIB_MAJOR version was 5 or higher. This approach did not correctly handle the API changes introduced in libgif version 5.1.0, leading to compilation issues with versions 5.0.X, where the API differences are still relevant.
The proposed change enhances the version check to consider both the major and minor version numbers. This ensures that the specific API changes introduced in version 5.1.0 and onwards are accurately accounted for, thus maintaining compatibility with version 5.0.X and addressing the compilation issues encountered.

Fix incorrect version check for libgif

---

dlib/simd/simd_check.h

MMX is not actually used by dlib and including the header breaks SIMD support detection and usage on platforms that support SSE but not MMX, such as emcc

Remove MMX header

---

tools/python/src/numpy_returns.cpp

This should've been added in #2925.
The only doubt I have around the function name:
- `load_rgb_alpha_image`: following the `rgb_alpha_pixel` in dlib
- `load_rgba_image`: shorter and maybe nicer?

Actually load rgb_alpha images.

---

dlib/global_optimization/find_max_global.h

Fixes error (``-Wmissing-template-arg-list-after-template-kw``) from clang-19 compiler.

global_optimization: add template argument list

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h

This PR introduces a new customizable dropout layer, `dropout_custom_`, which allows specifying the dropout rate at compile-time. This enhancement is particularly beneficial for deep neural networks with numerous layers, where manually setting different dropout rates for each layer can be cumbersome.
Key features and benefits:
1. Compile-time dropout rate specification: Allows for clearer and more concise network definitions.
2. Inherits from the existing `dropout_` class: Maintains all functionality of the original dropout layer.
3. Template-based implementation: Provides type-safety and potential performance benefits.
4. Includes a pre-defined `dropout_10` alias: Offers a convenient 10% dropout option for common use cases.

Add customizable dropout layer with compile-time rate specification

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/test/dnn.cpp

Fix layer_normalize gradients

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/dnn/visitors.h
dlib/dnn/visitors_abstract.h
dlib/test/dnn.cpp

This PR introduces a new RMS (Root Mean Square) Normalization layer to Dlib. RMS Normalization is a variant of Layer Normalization that has shown promising results in various deep learning tasks, particularly in Natural Language Processing.
Key changes:
- Add rms_norm_ class implementing the RMS Normalization layer
- Implement rms_normalize and rms_normalize_gradient utility functions
- Add CPU and CUDA implementations for RMS Normalization
- Include unit tests for the new layer
This new layer provides an alternative to the existing layer_norm_, offering potential performance benefits and improved training stability in certain scenarios.
Usage Example:
For a comprehensive example of how to use this new RMS Normalization layer in a Transformer-based architecture, please refer to the ERNIE …

Add RMS Normalization Layer

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/dnn/visitors.h
dlib/test/dnn.cpp

This PR introduces a new tril_ layer to dlib, which implements lower triangular matrix operations similar to PyTorch's torch.tril() function. The layer allows for flexible lower triangular matrix masking with customizable diagonal offset and diagonal value.
- Implements lower triangular masking for tensors
- Supports custom diagonal offset and diagonal value
- Offers three convenient alias templates: tril, tril_mask, and tril_diag
This addition enhances dlib's neural network capabilities, allowing for more complex architectures that require lower triangular matrix operations.
The new layer can be particularly useful in attention mechanisms, triangular matrix operations, and other scenarios where lower triangular masking is required in neural network architectures.

Add tril_ layer for lower triangular matrix operations

---

dlib/image_saver/save_jxl.h

The problem appeared when trying to save the empirical cross-correlation matrix using the result of a matrix expression.  That path was not taken into account by the JXL image saver.

Fix saving JXL generic grayscale images

---

tools/python/test/utils.py

That method has been deprecated in Python 3.12 and will be removed from
Python 3.14. Replace it with a direct call to
`importlib.util.find_spec()`, which `pkgutil.find_loader()` was wrapping
around.

Replace deprecated pkgutil.find_loader()

---

dlib/cmake_utils/find_blas.cmake
dlib/cmake_utils/test_for_cudnn/find_cudnn.txt

cmake unable to detect blas, lapack, intel mkl and cudnn on my windows 11 64 bit OS. I fixed the issue by suggesting these changes in find_blas.cmake and find_cudnn.txt which will help cmake to find out proper path of library and include files.

find blas and cudnn update for windows OS

---

examples/slm_basic_train_ex.cpp
examples/slm_data.h
examples/slm_defs.h

Just a few minor tweaks to align the example's style with other examples in dlib.
@Cydral, please check if you agree. And great job, btw!

minor tweaks to the transformer example

---

dlib/cuda/cpu_dlib.cpp
dlib/cuda/cpu_dlib.h
dlib/cuda/cuda_dlib.cu
dlib/cuda/cuda_dlib.h
dlib/cuda/tensor_tools.cpp
dlib/cuda/tensor_tools.h
dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/test/dnn.cpp

I am training a U-Net using the architecture from [U-Net: Convolutional Networks for Biomedical Image Segmentation](https://arxiv.org/pdf/1505.04597). It requires cropping the tensors from the encoding stages to concatenate with the outputs of the decoding stages. I created the slice layer to implement this.
AFAICK, there are no layers in dlib that accommodate this. However, I probably should have asked before creating this one.
Some of my considerations:
- It is similar to extract, but instead it copies non-contiguous regions to perform a 3D crop. This is both different behavior and performance.
- I could have used an alias_tensor, similarly to extract, by aliasing every row. The CPU implementation may have been similar performance doing this. However, this is not ideal with CUDA because …

Slice layer

---

dlib/external/zlib/inflate.c

Description
This PR fixes a security vulnerability in inflate() that was cloned from zlib but did not receive the security patch applied in zlib. The original issue was reported and fixed under https://github.com/madler/zlib/commit/eff308af425b67093bab25f80f1ae950166bece1.
This PR applies the same patch as the one in zlib to eliminate the vulnerability.
References
https://nvd.nist.gov/vuln/detail/CVE-2022-37434
https://github.com/madler/zlib/commit/eff308af425b67093bab25f80f1ae950166bece1

Fix: Potential Vulnerability in Cloned Function

---

dlib/any/storage.h

`throw()` has been deprecated since C++11 and is removed in C++20. `noexcept` is accepted alternative.

`throw()` -> `noexcept`

---

tools/python/src/sequence_segmenter.cpp

Solve build error when compiling with GCC 15.

Drop namespace std

---

dlib/test/queue.cpp
dlib/test/static_set.cpp
dlib/test/tokenizer.cpp
dlib/tokenizer.h
dlib/tokenizer/bpe_tokenizer.h
dlib/tokenizer/bpe_tokenizer_abstract.h
tools/htmlify/htmlify.cpp

This PR introduces a new `bpe_tokenizer` class to Dlib, implementing the **Byte Pair Encoding (BPE)** algorithm for subword tokenization. The BPE tokenizer is a widely used technique in natural language processing (NLP) for handling out-of-vocabulary words and reducing vocabulary size while maintaining text representation capabilities.
- **BPE Algorithm**: Implements the BPE algorithm as described in [Sennrich et al., 2016](https://arxiv.org/abs/1508.07909).
- **Special Tokens**: Supports predefined special tokens (e.g., `<text>`, `<url>`, `<image>`) for marking specific elements in the text.
- **Training and Encoding**: Provides methods for training the tokenizer on a text corpus and encoding/decoding text into subword tokens.
- **Serialization**: Supports saving and loading the …

Add Byte Pair Encoding (BPE) class for subword tokenization

---

setup.py

Newer python versions raise a syntax warning when installing dlib.
```
<string>:235: SyntaxWarning: invalid escape sequence '\('
<string>:236: SyntaxWarning: invalid escape sequence '\('
<string>:237: SyntaxWarning: invalid escape sequence '\('
```

Fix SyntaxWarning in setup.py

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/test/dnn.cpp

This PR adds a new `linear_` layer that provides an optimized linear transformation for multi-dimensional inputs. The layer preserves the spatial dimensions of the input tensor while transforming the feature dimension.
**Features**
- Supports both biased and unbiased linear transformations
- Optimized for maintaining tensor dimensions (except for feature dimension)
- Compatible with existing DNN API patterns and serialization
This implementation is more efficient than reshaping inputs to use fc_ layers when working with multi-dimensional data.
Similar functionality exists in other major frameworks like PyTorch (`nn.Linear`), which operates on the last dimension while preserving other dimensions.

Add linear_ layer for neural networks

---

dlib/dnn/layers.h
dlib/dnn/layers_abstract.h
dlib/dnn/visitors.h
dlib/test/dnn.cpp

This implements a new layer that reshapes or resizes tensors with two operation modes:
1. Pure Reshape Mode:
- When input/output element counts match: simple tensor reshaping without value changes.
3. Spatial Rescaling Mode (similar to `resize_to` existing layer):
- When only spatial dimensions change: uses bilinear interpolation while preserving channels.
Includes `flatten` alias for common flattening operations

Add `reshape_to` layer for flexible tensor reshaping/rescaling

---

docs/docs/compile.xml

update the `compile.xml` to reflect that dlib requires c++14 now.

docs: dlib requires c++14

---

dlib/dnn/loss.h

The gradient calculation for bounding box x and y coordinates in the `loss_yolo_` helper `impl::yolo_helper_impl::tensor_to_loss` was missing a factor of 2.0. This factor arises from the chain rule due to the coordinate transformation `output_scaled = network_output * 2.0 - 0.5`, where the loss is calculated based on `output_scaled`, but the gradient needs to be with respect to `network_output`.
This commit multiplies the affected gradient terms by 2.0f to correctly apply the chain rule.

Fix: Correct YOLO loss gradient for x,y coordinates

---

dlib/matlab/cmake_mex_wrapper

'\dlib\matlab\cmake_mex_wrapper' missed including the library 'libut.lib', which leads to a link error of 'undefined reference to utIsInterruptPending'. The version fix the error by adding 2 lines (line 41 & 46), and append ' ${MATLAB_UT_LIBRARY}' in line 48 in '\dlib\matlab\cmake_mex_wrapper'

fix the miss of including matlab ut library

---

dlib/array2d/array2d_generic_image.h
dlib/array2d/array2d_kernel.h
dlib/array2d/array2d_kernel_abstract.h
dlib/image_processing/generic_image.h
dlib/image_transforms/interpolation.h
dlib/matrix/matrix_generic_image.h
dlib/opencv/cv_image.h
dlib/opencv/cv_image_abstract.h
dlib/python/numpy_image.h

Problem: reading large images (in my case, it was a 40792x20480 RGBA PNG one) causes a crash, when the product _row number_ * _width step_ overflows a 32-bit integer
Solution: change the type of the width step to be `size_t` (and not `long`)

Fix numeric overflow when accessing pixel data of very large images

---

tools/python/test/test_numpy_returns.py

Python has changed the way references are counted (borrowed references)
in version 3.14.
Close #3096

Account for change in ref count in Python 3.14+

---

dlib/any/storage.h

This is the pull request which solves [this corresponding bug](https://github.com/davisking/dlib/issues/3097). 
Note that while trying to test it, I was unable to run all of the tests, as the makefile to build the tests would fail with 
```
../dlib/dnn/layers.h:2447:25: error: casting ‘dlib::alias_tensor_const_instance’ to ‘dlib::tensor&’ does not use 
‘dlib::alias_tensor_const_instance::operator const dlib::tensor&()’ [-Werror=cast-user-defined]
2447 |             tt::gemm(1, (tensor&)sgi, 1, gi, false, w, true);
|                         ^~~~~~~~~~~~
```
However, this would happen on master as well, so this isn't the fault of my patch.

std::aligned_storage_t is deprecated in c++23

---

dlib/dnn/layers.h

The tests compile and run mostly. I get deprecated warnings for something in ffmpeg which can an error on one of the final tests. I am not enough of an expert at cmake to understand why only some of the files are compiled with -Werror. 
Please look carefully at this pull request as I turned something that was `const` into non-`const`. I am not convinced it is correct. Though the c-style cast was likely modifying a `const` variable through a non-`const` reference anyway.
`static_cast` did not work. 
I am planning on adding a flag to the `CMakelist.txt` test file that lets me turn off `-Werror` so I can at least fully test changes before submitting them. Particularly while I am patching away warnings like this.

fix -Wcast-user-defined warning
